#!/usr/bin/env python3
"""Write the API backend Compose env file from deployed config inputs.

The generated file is an operational artifact and must not be committed.
This helper intentionally prints key names only, never values.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import uuid
from typing import Any

DEFAULT_PORT_OFFSETS = {
    "NOVAIC_ENTANGLED_PORT": 0,
    "NOVAIC_RUNTIME_SCHEDULER_PORT": 83,
    "NOVAIC_RUNTIME_HEALTH_PORT": 84,
    "NOVAIC_SUBSCRIBER_PORT": 85,
    "NOVAIC_REGISTRY_PORT": 91,
    "NOVAIC_DEVICE_PORT": 93,
    "NOVAIC_SANDBOX_PORT": 94,
    "NOVAIC_BLOB_PORT": 95,
    "NOVAIC_CORTEX_PORT": 96,
    "NOVAIC_QUEUE_PORT": 97,
    "NOVAIC_BUSINESS_PORT": 98,
    "NOVAIC_GATEWAY_PORT": 99,
}


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _deep_overlay(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_overlay(base[key], value)
        else:
            base[key] = value
    return base


def _apply_secret_overlay(raw: dict[str, Any], path: Path) -> None:
    overlay = _load_json(path)
    if "secrets" in overlay and len(overlay) == 1:
        overlay_secrets = overlay["secrets"]
    else:
        overlay_secrets = overlay
    if not isinstance(overlay_secrets, dict):
        raise ValueError(f"{path} must contain a secrets object")

    base = raw.setdefault("secrets", {})
    if not isinstance(base, dict):
        raise ValueError("services.json secrets must be an object")

    unknown = sorted(set(overlay_secrets) - set(base))
    if unknown:
        raise ValueError(f"{path} contains unknown secret keys: {unknown}")

    for key, value in overlay_secrets.items():
        if value is not None and not isinstance(value, str):
            raise ValueError(f"{path}: secrets.{key} must be a string")
        base[key] = value or ""


def _required(raw: dict[str, Any], section: str, key: str, source: str = "config") -> str:
    value = raw.get(section, {}).get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"missing required {source} value: {section}.{key}")
    if "\n" in value or "\r" in value:
        raise ValueError(f"{source} value contains newline: {section}.{key}")
    return value


def _optional(raw: dict[str, Any], section: str, key: str, default: str) -> str:
    value = raw.get(section, {}).get(key, default)
    if value is None:
        return default
    if not isinstance(value, str):
        raise ValueError(f"services.json value must be a string: {section}.{key}")
    if "\n" in value or "\r" in value:
        raise ValueError(f"services.json value contains newline: {section}.{key}")
    return value or default


def _write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp")
    previous_umask = os.umask(0o177)
    try:
        with tmp.open("w", encoding="utf-8") as handle:
            handle.write("# Generated by docker/api-backend/write_env.py; do not commit.\n")
            for key, value in values.items():
                if "\n" in value or "\r" in value:
                    raise ValueError(f"env value contains newline: {key}")
                handle.write(f"{key}={value}\n")
        tmp.chmod(0o600)
        tmp.replace(path)
        path.chmod(0o600)
    finally:
        tmp.unlink(missing_ok=True)
        os.umask(previous_umask)


def _env_default(key: str, default: str) -> str:
    value = os.environ.get(key)
    return value if value not in {None, ""} else default


def _default_port_base(namespace: str) -> int:
    if namespace == "staging":
        return 29900
    if namespace.startswith("preview-pr-"):
        return 39000
    return 19900


def _default_redis_url(namespace: str) -> str:
    if namespace == "staging":
        return "redis://127.0.0.1:6379/1"
    return "redis://127.0.0.1:6379/0"


def _port_values(port_base: int) -> dict[str, str]:
    values: dict[str, str] = {"NOVAIC_PORT_BASE": str(port_base)}
    for key, offset in DEFAULT_PORT_OFFSETS.items():
        values[key] = _env_default(key, str(port_base + offset))
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate API backend Compose env file")
    parser.add_argument("--services-json", required=True, type=Path)
    parser.add_argument("--runtime-switches", type=Path)
    parser.add_argument("--secrets-json", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--image", default="novaic/api-backend:local")
    parser.add_argument("--namespace", default=os.environ.get("NOVAIC_NAMESPACE", "prod"))
    parser.add_argument("--release-id", default=os.environ.get("NOVAIC_RELEASE_ID", "local-build"))
    parser.add_argument("--environment", default=os.environ.get("NOVAIC_ENVIRONMENT", ""))
    parser.add_argument("--host-id", default=os.environ.get("NOVAIC_HOST_ID", "api-host-1"))
    parser.add_argument("--compose-project", default=os.environ.get("COMPOSE_PROJECT_NAME", ""))
    parser.add_argument("--image-digest", default=os.environ.get("NOVAIC_IMAGE_DIGEST", ""))
    parser.add_argument("--data-dir", default=os.environ.get("NOVAIC_DATA_DIR", ""))
    parser.add_argument("--postgres-secrets-dir", default=os.environ.get("NOVAIC_POSTGRES_SECRETS_DIR", ""))
    parser.add_argument("--etc-dir", default=os.environ.get("NOVAIC_ETC_DIR", ""))
    parser.add_argument("--redis-url", default=os.environ.get("NOVAIC_REDIS_URL", ""))
    parser.add_argument("--registry-table", default=os.environ.get("NOVAIC_REGISTRY_TABLE", "service_registry_instances"))
    parser.add_argument("--port-base", type=int, default=int(os.environ.get("NOVAIC_PORT_BASE", "0") or 0))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    raw = _load_json(args.services_json)
    if args.runtime_switches and args.runtime_switches.exists():
        _deep_overlay(raw, _load_json(args.runtime_switches))
    if not args.secrets_json.exists():
        raise ValueError(f"missing required secrets file: {args.secrets_json}")
    _apply_secret_overlay(raw, args.secrets_json)

    namespace = args.namespace.strip()
    if not namespace:
        raise ValueError("--namespace must not be empty")
    port_base = args.port_base or _default_port_base(namespace)
    registry_port = _env_default("NOVAIC_REGISTRY_PORT", str(port_base + DEFAULT_PORT_OFFSETS["NOVAIC_REGISTRY_PORT"]))
    data_dir = args.data_dir or f"/opt/novaic/data/{namespace}"

    values = {
        "COMPOSE_PROJECT_NAME": args.compose_project or f"novaic-{namespace}",
        "NOVAIC_NAMESPACE": namespace,
        "NOVAIC_RELEASE_ID": args.release_id,
        "NOVAIC_HOST_ID": args.host_id,
        "NOVAIC_ENVIRONMENT": args.environment or namespace,
        "NOVAIC_IMAGE_DIGEST": args.image_digest,
        "NOVAIC_API_BACKEND_IMAGE": args.image,
        "NOVAIC_DATA_DIR": data_dir,
        "NOVAIC_SANDBOX_SHARED_DIR": _env_default(
            "NOVAIC_SANDBOX_SHARED_DIR",
            f"{data_dir}/sandbox",
        ),
        "NOVAIC_POSTGRES_SECRETS_DIR": args.postgres_secrets_dir
        or f"/opt/novaic/postgres/secrets/{namespace}",
        "NOVAIC_ETC_DIR": args.etc_dir or f"/opt/novaic/etc/{namespace}",
        "NOVAIC_SERVICE_REGISTRY_URL": _env_default(
            "NOVAIC_SERVICE_REGISTRY_URL",
            f"http://127.0.0.1:{registry_port}",
        ),
        "NOVAIC_REGISTRY_TABLE": args.registry_table,
        "NOVAIC_REDIS_URL": args.redis_url or _default_redis_url(namespace),
        "NOVAIC_ENTANGLED_SERVICE_TOKEN_FILE": _env_default(
            "NOVAIC_ENTANGLED_SERVICE_TOKEN_FILE",
            "/opt/novaic/postgres/secrets/entangled_service_token",
        ),
        "NOVAIC_JWT_SECRET": _required(raw, "secrets", "jwt_secret", "secret"),
        "NOVAIC_CORTEX_INTERNAL_KEY": _optional(
            raw, "secrets", "cortex_internal_key", ""
        ),
        "NOVAIC_BLOB_BACKEND": "oss",
        "NOVAIC_OSS_ACCESS_KEY": _required(raw, "secrets", "alibaba_cloud_access_key_id", "secret"),
        "NOVAIC_OSS_SECRET_KEY": _required(raw, "secrets", "alibaba_cloud_access_key_secret", "secret"),
        "NOVAIC_OSS_ENDPOINT": _required(raw, "blob_storage", "oss_endpoint"),
        "NOVAIC_OSS_REGION": _required(raw, "blob_storage", "oss_region"),
        "NOVAIC_OSS_BUCKET": _required(raw, "blob_storage", "oss_bucket"),
    }
    values.update(_port_values(port_base))
    values["NOVAIC_REGISTRY_PORT"] = registry_port
    _write_env(args.output, values)
    print(f"wrote {args.output} with keys: {', '.join(values)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
