"""
RuntimeLauncher

Creates Runtime and MCP servers for awake SubAgents.

Pre-logic:
- Create Runtime record
- Create MCP servers (Agent shared, Runtime, Aggregate)
- Update Runtime with MCP URL

This launcher creates no async tasks - MCP creation is synchronous.
"""

import json
import uuid
import time
import asyncio
from typing import Dict, Any, Optional, TYPE_CHECKING
import aiohttp

from ..launcher_worker import BaseLauncher, LauncherWorker
from ..base import RetryableError

if TYPE_CHECKING:
    from ..gateway_client import GatewayClient


@LauncherWorker.register("runtime_launcher")
class RuntimeLauncher(BaseLauncher):
    """
    Launcher that creates Runtime and MCP servers.
    
    Creates:
    - Runtime record via Gateway API
    - MCP servers via MCP Gateway API
    """
    
    async def prepare_and_launch(
        self,
        task: dict,
        runtime_id: str,
        stage_id: str,
        agent_id: str,
        args: dict,
    ) -> dict:
        """
        Create Runtime and MCP servers.
        
        This method is atomic: if MCP creation fails, the Runtime record
        is cleaned up to avoid leaving orphan records.
        """
        # Get agent_id and subagent_id from args (REQUIRED - no fallback to "system")
        actual_agent_id = args.get("agent_id")
        subagent_id = args.get("subagent_id")
        
        if not actual_agent_id:
            raise ValueError(f"agent_id required in args for runtime_launcher: {args}")
        
        if not subagent_id:
            raise ValueError(f"subagent_id required in args for runtime_launcher: {args}")
        
        # Get agent_index
        agent_index = await self._get_agent_index(actual_agent_id)
        
        # Create Runtime record
        new_runtime_id = await self.client.create_runtime(
            runtime_id="",  # Will be generated by API
            subagent_id=subagent_id,
            agent_id=actual_agent_id,
        )
        
        # Create MCP servers (with rollback on failure)
        try:
            mcp_url = await self._create_mcp_servers(actual_agent_id, new_runtime_id, subagent_id, agent_index)
            
            if not mcp_url:
                # MCP creation returned None - cleanup and retry
                raise RetryableError(f"MCP creation returned None for runtime {new_runtime_id}")
            
            await self.client.update_runtime(new_runtime_id, mcp_url=mcp_url)
                
        except Exception as e:
            # Rollback: delete the Runtime record to avoid orphan
            print(f"[RuntimeLauncher] MCP creation failed, rolling back runtime {new_runtime_id}: {e}")
            try:
                await self.client.delete_runtime(new_runtime_id)
                print(f"[RuntimeLauncher] Rolled back runtime {new_runtime_id}")
            except Exception as cleanup_error:
                print(f"[RuntimeLauncher] Warning: failed to cleanup runtime {new_runtime_id}: {cleanup_error}")
            
            # Convert to RetryableError if not already
            if isinstance(e, RetryableError):
                raise
            raise RetryableError(f"MCP creation failed: {e}")
        
        # Note: SubAgent status (awaking → awake) is set by RuntimeCollector
        # after verifying MCP creation success
        
        return {
            "async_task_ids": [],  # No async tasks
            "collector_args": {
                "agent_id": actual_agent_id,  # REQUIRED for next tasks
                "new_runtime_id": new_runtime_id,
                "mcp_url": mcp_url,
                "subagent_id": subagent_id,
            },
            "next_stage_type": "think_launcher",  # Always go to think
        }
    
    async def _get_agent_index(self, agent_id: str) -> int:
        """Get agent_index from agent config."""
        try:
            agent = await self.client.get_agent(agent_id)
            
            if agent:
                vm_config = agent.get("vm_config", {})
                if isinstance(vm_config, str):
                    try:
                        vm_config = json.loads(vm_config)
                    except:
                        vm_config = {}
                return vm_config.get("agent_index", 0) if isinstance(vm_config, dict) else 0
        except:
            pass
        return 0
    
    async def _create_mcp_servers(
        self, 
        agent_id: str, 
        runtime_id: str, 
        subagent_id: str,
        agent_index: int
    ) -> Optional[str]:
        """Create MCP servers via MCP Gateway API."""
        try:
            # Step 1: Create Agent shared layer MCP (if not exists)
            if not await self.client.has_agent_shared_mcp(agent_id):
                await self.client.create_agent_shared_mcp(agent_id, agent_index)
            
            # Step 2: Create Runtime MCP
            await self.client.create_runtime_mcp(agent_id, runtime_id, subagent_id, agent_index)
            
            # Step 3: Create Aggregate MCP
            mcp_url = await self.client.create_aggregate_mcp(agent_id, runtime_id, subagent_id, agent_index)
            
            # Step 4: Wait for tool discovery
            await self._wait_for_tool_discovery(mcp_url)
            
            return mcp_url
            
        except Exception as e:
            print(f"[RuntimeLauncher] Error creating MCP: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    async def _wait_for_tool_discovery(
        self, 
        mcp_url: str, 
        min_tools: int = 10, 
        timeout: float = 5.0
    ):
        """Wait for MCP tool discovery."""
        start_time = time.time()
        poll_interval = 0.3
        
        async with aiohttp.ClientSession() as session:
            while time.time() - start_time < timeout:
                try:
                    async with session.post(
                        f"{mcp_url}sse",
                        json={
                            "jsonrpc": "2.0",
                            "method": "initialize",
                            "params": {
                                "protocolVersion": "2024-11-05",
                                "capabilities": {},
                                "clientInfo": {"name": "runtime-launcher", "version": "1.0"}
                            },
                            "id": 1
                        },
                        timeout=aiohttp.ClientTimeout(total=2),
                    ) as resp:
                        if resp.status != 200:
                            await asyncio.sleep(poll_interval)
                            continue
                        
                        session_id = resp.headers.get("mcp-session-id")
                        if not session_id:
                            await asyncio.sleep(poll_interval)
                            continue
                        
                        await resp.read()
                    
                    async with session.post(
                        f"{mcp_url}sse",
                        json={"jsonrpc": "2.0", "method": "tools/list", "id": 2},
                        headers={"mcp-session-id": session_id},
                        timeout=aiohttp.ClientTimeout(total=2),
                    ) as resp:
                        if resp.status != 200:
                            await asyncio.sleep(poll_interval)
                            continue
                        
                        content = await resp.text()
                        for line in content.split('\n'):
                            if line.startswith('data:'):
                                data = json.loads(line[5:].strip())
                                tools = data.get("result", {}).get("tools", [])
                                if len(tools) >= min_tools:
                                    return True
                        
                except Exception:
                    pass
                
                await asyncio.sleep(poll_interval)
        
        return False
