"""
Internal API module: agent

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Agent Operations ====================

@router.get("/agents/setup-complete")
def get_setup_complete_agents():
    """Get all agents with setup complete."""
    from gateway.db.repositories import AgentRepository
    
    db = get_db()
    agent_repo = AgentRepository(db)
    agent_ids = agent_repo.list_setup_complete_ids()
    
    return {"agent_ids": agent_ids}


@router.post("/agents/{agent_id}/awake")
def set_agent_awake(agent_id: str):
    """Set agent state to awake."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    repo.set_awake(agent_id)
    
    return {"status": "ok"}


@router.post("/agents/{agent_id}/sleep")
def set_agent_sleep(agent_id: str, data: Dict[str, Any] = None):
    """Set agent state to sleep."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    reason = (data or {}).get("reason", "Task completed")
    repo.set_sleep(agent_id, reason=reason)
    
    return {"status": "ok"}


@router.get("/agents/{agent_id}")
def get_agent_internal(agent_id: str):
    """Get agent information for internal use (tools server)."""
    from gateway.config import get_agent_config_manager
    
    agent_manager = get_agent_config_manager()
    agent = agent_manager.get_agent(agent_id)
    
    if not agent:
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")
    
    # Return agent data with VM ports for tools server
    return {
        "agent_id": agent.agent_id,
        "name": agent.name,
        "vm": {
            "backend": agent.vm.backend if agent.vm else None,
            "ports": {
                "ssh": agent.vm.ports.ssh if agent.vm and agent.vm.ports else None,
                "vmuse": agent.vm.ports.vmuse if agent.vm and agent.vm.ports else None,
            } if agent.vm and agent.vm.ports else {}
        } if agent.vm else {}
    }


# 工具服务由 Backend 组件 Tools Server 提供（api/internal_mcp.py）；Master 调 Tools Server /internal/mcp/*
