"""
Internal API module: agent

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Agent Operations ====================

@router.get("/agents/setup-complete")
def get_setup_complete_agents():
    """Get all agents with setup complete."""
    from gateway.db.repositories import AgentRepository
    
    db = get_db()
    agent_repo = AgentRepository(db)
    agent_ids = agent_repo.list_setup_complete_ids()
    
    return {"agent_ids": agent_ids}


@router.post("/agents/{agent_id}/awake")
def set_agent_awake(agent_id: str):
    """Set agent state to awake."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    repo.set_awake(agent_id)
    
    return {"status": "ok"}


@router.post("/agents/{agent_id}/sleep")
def set_agent_sleep(agent_id: str, data: Dict[str, Any] = None):
    """Set agent state to sleep."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    reason = (data or {}).get("reason", "Task completed")
    repo.set_sleep(agent_id, reason=reason)
    
    return {"status": "ok"}


@router.get("/agents/{agent_id}")
def get_agent_internal(agent_id: str):
    """Get agent information for internal use (tools server).
    
    Returns vm.ports and android for VM tools (screenshot, desktop) and Mobile tools
    (mobile_screenshot, etc.). Uses unified devices (v38) when legacy agent.vm / agent.android
    are empty.
    """
    from gateway.config import get_agent_config_manager
    
    agent_manager = get_agent_config_manager()
    agent = agent_manager.get_agent(agent_id)
    
    if not agent:
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")
    
    # Build vm.ports - from legacy agent.vm or from devices (Linux device)
    vm_ports = {"ssh": None, "vmuse": None}
    if agent.vm and agent.vm.ports and (agent.vm.ports.ssh or agent.vm.ports.vmuse):
        vm_ports["ssh"] = agent.vm.ports.ssh or None
        vm_ports["vmuse"] = agent.vm.ports.vmuse or None
    # Fallback: get from first Linux device (v38 unified model)
    if not vm_ports["vmuse"] and getattr(agent, "devices", None):
        for d in agent.devices:
            if isinstance(d, dict) and d.get("type") == "linux":
                ports = d.get("ports") or {}
                if ports.get("vmuse"):
                    vm_ports["ssh"] = ports.get("ssh")
                    vm_ports["vmuse"] = ports.get("vmuse")
                    break
            elif hasattr(d, "type") and getattr(d, "type", None) == "linux":
                ports = getattr(d, "ports", None) or {}
                if ports.get("vmuse"):
                    vm_ports["ssh"] = ports.get("ssh")
                    vm_ports["vmuse"] = ports.get("vmuse")
                    break
    
    result = {
        "agent_id": agent.id,
        "name": agent.name,
        "vm": {
            "backend": agent.vm.backend if agent.vm else None,
            "ports": vm_ports,
        } if agent.vm or vm_ports["vmuse"] else {}
    }
    
    # Build android config - from legacy agent.android or from devices (Android device)
    android_config = None
    if agent.android and agent.android.device_serial:
        android_config = {
            "device_serial": agent.android.device_serial,
            "managed": agent.android.managed,
            "avd_name": agent.android.avd_name,
        }
    # Fallback: get from first Android device (v38 unified model)
    if not android_config and getattr(agent, "devices", None):
        for d in agent.devices:
            if isinstance(d, dict) and d.get("type") == "android":
                serial = d.get("device_serial") or d.get("avd_name")
                if serial or d.get("avd_name"):
                    android_config = {
                        "device_serial": d.get("device_serial", ""),
                        "managed": d.get("managed", True),
                        "avd_name": d.get("avd_name", ""),
                    }
                    break
            elif hasattr(d, "type") and getattr(d, "type", None) == "android":
                serial = getattr(d, "device_serial", None) or getattr(d, "avd_name", None)
                if serial:
                    android_config = {
                        "device_serial": getattr(d, "device_serial", "") or "",
                        "managed": getattr(d, "managed", True),
                        "avd_name": getattr(d, "avd_name", ""),
                    }
                    break
    
    if android_config:
        result["android"] = android_config
    
    return result


@router.get("/agents/{agent_id}/memory/all")
def get_all_agent_memory(agent_id: str):
    """Get all memory data for an agent (all namespaces).
    
    Used by system_prompt builder to auto-load memory into system prompt.
    
    Returns:
        {
            "success": True,
            "namespaces": {
                "default": {"key1": "value1", ...},
                "preferences": {...},
                ...
            }
        }
    """
    from gateway.db.repositories.memory import MemoryRepository
    
    db = get_db()
    repo = MemoryRepository(db)
    
    # Get all namespaces
    namespaces = repo.list_namespaces(agent_id)
    
    # Get all data from each namespace
    result = {}
    for ns in namespaces:
        ns_data = repo.recall(agent_id=agent_id, key=None, namespace=ns)
        if ns_data.get("success"):
            result[ns] = ns_data.get("memories", {})
    
    return {
        "success": True,
        "namespaces": result
    }


# 工具服务由 Backend 组件 Tools Server 提供（api/internal_mcp.py）；Master 调 Tools Server /internal/mcp/*
