"""
Internal API module: agent

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Agent Operations ====================

@router.get("/agents/setup-complete")
def get_setup_complete_agents():
    """Get all agents with setup complete."""
    from gateway.db.repositories import AgentRepository
    
    db = get_db()
    agent_repo = AgentRepository(db)
    agent_ids = agent_repo.list_setup_complete_ids()
    
    return {"agent_ids": agent_ids}


@router.post("/agents/{agent_id}/awake")
def set_agent_awake(agent_id: str):
    """Set agent state to awake."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    repo.set_awake(agent_id)
    
    return {"status": "ok"}


@router.post("/agents/{agent_id}/sleep")
def set_agent_sleep(agent_id: str, data: Dict[str, Any] = None):
    """Set agent state to sleep."""
    from gateway.db.repositories import AgentStateRepository
    
    db = get_db()
    repo = AgentStateRepository(db)
    reason = (data or {}).get("reason", "Task completed")
    repo.set_sleep(agent_id, reason=reason)
    
    return {"status": "ok"}


# 工具服务由 Backend 组件 Tools Server 提供（api/internal_mcp.py）；Master 调 Tools Server /internal/mcp/*
