"""
Internal API module: config

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Config ====================

@router.get("/config/agent/{agent_id}")
def get_agent_config(agent_id: str):
    """Get agent configuration."""
    from gateway.config.agents import get_agent_config_manager
    
    agent_mgr = get_agent_config_manager()
    agent = agent_mgr.get_agent(agent_id)
    
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")
    
    return {
        "id": agent.id,
        "name": agent.name,
        "default_model": agent.default_model,
    }


@router.get("/config/ports/by-agent/{agent_id}")
def get_ports_by_agent_id(agent_id: str):
    """
    Get port configuration for an agent by agent_id.
    
    Retrieves ports from agent configuration in database.
    """
    from gateway.config.agents import GATEWAY_PORT, BASE_PORT, PORTS_PER_AGENT
    
    agent_mgr = get_agent_config_manager()
    agent = agent_mgr.get_agent(agent_id)
    
    if not agent or not agent.vm or not agent.vm.ports:
        raise HTTPException(status_code=404, detail="Agent not found or has no port configuration")
    
    ports = agent.vm.ports
    return {
        "agent_id": agent_id,
        "gateway_port": GATEWAY_PORT,
        "base_port": BASE_PORT,
        "ports_per_agent": PORTS_PER_AGENT,
        "ports": {
            "ssh": ports.ssh,
        }
    }


@router.get("/config/llm")
def get_llm_config():
    """
    Get LLM configuration (API keys and models).
    
    Used by Worker processes that need to call LLM.
    Returns sanitized config (no full API keys exposed).
    """
    from gateway.config import get_config_manager
    
    config = get_config_manager().load()
    
    # Group models by api_key_id
    models_by_key = {}
    for m in config.candidate_models:
        if m.api_key_id not in models_by_key:
            models_by_key[m.api_key_id] = []
        models_by_key[m.api_key_id].append({
            "id": m.id,
            "name": m.name,
            "enabled": m.enabled,
            "is_custom": m.is_custom,
        })
    
    return {
        "default_model": config.default_model,
        "api_keys": [
            {
                "id": key.id,
                "provider": key.provider.value if hasattr(key.provider, 'value') else str(key.provider),
                "name": key.name,
                "api_base": key.api_base,
                # Only return masked key for security
                "api_key_masked": key.api_key[:8] + "..." if key.api_key else None,
                "candidate_models": models_by_key.get(key.id, [])
            }
            for key in config.api_keys
        ]
    }


@router.get("/config/llm/full")
def get_llm_config_full():
    """
    Get full LLM configuration including API keys.
    
    INTERNAL USE ONLY - includes sensitive data.
    Used by task_queue workers for LLM calls.
    
    Returns model config for the default_model, including:
    - model: model name
    - provider: openai/anthropic/google
    - api_key: full API key
    - api_base: API base URL
    """
    from gateway.config import get_config_manager
    
    config = get_config_manager().load()
    
    # Find the model config for default_model
    default_model_info = next(
        (m for m in config.candidate_models if m.name == config.default_model),
        None
    )
    
    if not default_model_info:
        return {
            "success": False,
            "error": f"Default model '{config.default_model}' not found in candidate_models",
            "default_model": config.default_model,
            "candidate_models": [m.name for m in config.candidate_models],
        }
    
    # Get the API key for this model
    api_key_entry = config.get_api_key_by_id(default_model_info.api_key_id)
    
    if not api_key_entry:
        return {
            "success": False,
            "error": f"API key not found for model '{config.default_model}'",
            "default_model": config.default_model,
        }
    
    return {
        "success": True,
        "default_model": config.default_model,
        "model_config": {
            "model": default_model_info.name,
            "provider": api_key_entry.provider.value if hasattr(api_key_entry.provider, 'value') else str(api_key_entry.provider),
            "api_key": api_key_entry.api_key,
            "api_base": api_key_entry.get_effective_base_url(),
        }
    }


def _build_llm_config_for_agent(db, agent_id: str) -> Dict[str, Any]:
    """Build LLM config for a specific agent (internal helper)."""
    
    # 1. Check agent exists and get its model_id
    with db.get_connection("agent", resource_id=agent_id, timeout=ServiceConfig.DB_TRANSACTION_TIMEOUT) as conn:
        cursor = conn.execute(
            "SELECT id, model_id FROM agents WHERE id = ?",
            (agent_id,)
        )
        row = cursor.fetchone()
    
    if not row:
        return {
            "success": False,
            "error": f"Agent '{agent_id}' not found",
            "agent_id": agent_id,
        }
    
    agent_model_id = row[1] if row[1] else None
    
    # 2. Use agent's model_id if set, otherwise use default model from config
    if agent_model_id:
        model_id = agent_model_id
    else:
        with db.get_connection("global", timeout=ServiceConfig.DB_TRANSACTION_TIMEOUT) as conn:
            cursor = conn.execute("SELECT value FROM config WHERE key = 'default_model'")
            default_row = cursor.fetchone()
        model_id = default_row[0].strip('"') if default_row else "gpt-4o"
    
    # 3. 从DB查询model和api_key配置
    with db.get_connection("global", timeout=ServiceConfig.DB_TRANSACTION_TIMEOUT) as conn:
        cursor = conn.execute("""
            SELECT 
                m.id as model_id,
                m.provider,
                k.provider as key_provider,
                k.api_key,
                k.api_base
            FROM candidate_models m
            JOIN api_keys k ON m.api_key_id = k.id
            WHERE m.id = ? AND m.available = 1
            LIMIT 1
        """, (model_id,))
        row = cursor.fetchone()
    
    if not row:
        return {
            "success": False,
            "error": f"Model '{model_id}' not found in candidate_models",
            "agent_id": agent_id,
            "model_id": model_id,
        }
    
    if not row[3]:  # api_key
        return {
            "success": False,
            "error": f"API key not configured for model '{model_id}'",
            "agent_id": agent_id,
            "model_id": model_id,
        }
    
    # 使用model表的provider或api_key表的provider
    provider = row[1] if row[1] else row[2]
    api_base = row[4] if row[4] else "https://api.openai.com/v1"
    
    return {
        "success": True,
        "agent_id": agent_id,
        "model": row[0],  # model_id (e.g. "kimi-k2.5")
        "provider": provider,
        "api_key": row[3],  # api_key
        "api_base": api_base,
    }


@router.get("/config/llm/agent/{agent_id}")
def get_agent_llm_config(agent_id: str):
    """
    Get LLM configuration for a specific agent.
    
    INTERNAL USE ONLY - includes sensitive data.
    Used by task_queue workers for LLM calls.
    
    Logic:
    1. If agent has model_id set, use that model
    2. Otherwise, use system default_model
    
    Returns:
    - success: bool
    - agent_id: str
    - model: model name
    - provider: openai/anthropic/google  
    - api_key: full API key
    - api_base: API base URL
    """
    db = get_db()
    return _build_llm_config_for_agent(db, agent_id)


@router.get("/config/llm/runtime/{runtime_id}")
def get_runtime_llm_config(runtime_id: str):
    """
    Get LLM configuration for a specific runtime.
    
    INTERNAL USE ONLY - includes sensitive data.
    Used by task_queue workers for LLM calls.
    
    Logic:
    1. Resolve agent_id and subagent_id from runtime_id
    2. Use agent's model_id if set, else default_model
    
    Returns:
    - success: bool
    - agent_id: str
    - subagent_id: str (e.g. "main-7b053af9")
    - model: model name
    - provider: openai/anthropic/google  
    - api_key: full API key
    - api_base: API base URL
    """
    
    db = get_db()
    runtime_ctx = get_runtime_context(runtime_id)
    agent_id = runtime_ctx.get("agent_id")
    subagent_id = runtime_ctx.get("subagent_id", "main")
    
    # Get LLM config for agent
    result = _build_llm_config_for_agent(db, agent_id)
    
    # Add subagent_id to result (needed for execution_log broadcast)
    result["subagent_id"] = subagent_id
    
    return result
