"""
Internal API module: health

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Health Monitor Operations (v18) ====================

@router.get("/health/stuck-sending")
def get_stuck_sending_count(timeout_seconds: int = None):
    """Get count of messages stuck in 'sending' state."""
    if timeout_seconds is None:
        timeout_seconds = ServiceConfig.STUCK_SENDING_TIMEOUT
    from gateway.db.repositories import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    count = repo.reset_stuck_sending(timeout_seconds)
    
    return {"count": count}


# DELETED: stuck-awaking APIs - v3 删除 awaking 状态，用 get_or_create_runtime 替代
