"""
Internal API module: health

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(prefix="/internal", tags=["internal"])

# ==================== Health Monitor Operations (v18) ====================

@router.get("/health/stuck-sending")
def get_stuck_sending_count(timeout_seconds: int = None):
    """Get count of messages stuck in 'sending' state."""
    if timeout_seconds is None:
        timeout_seconds = ServiceConfig.STUCK_SENDING_TIMEOUT
    from gateway.db.repositories import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    count = repo.reset_stuck_sending(timeout_seconds)
    
    return {"count": count}


@router.get("/health/stuck-awaking")
def get_stuck_awaking_count(timeout_seconds: int = None):
    """Get count of SubAgents stuck in 'awaking' state."""
    if timeout_seconds is None:
        timeout_seconds = ServiceConfig.STUCK_AWAKING_TIMEOUT
    from gateway.db.repositories import SubAgentRepository
    
    db = get_db()
    repo = SubAgentRepository(db)
    count = repo.get_stuck_awaking_count(timeout_seconds)
    
    return {"count": count}


@router.post("/health/reset-stuck-awaking")
def reset_stuck_awaking(timeout_seconds: int = None):
    """Reset SubAgents stuck in 'awaking' state to 'sleeping'."""
    if timeout_seconds is None:
        timeout_seconds = ServiceConfig.STUCK_AWAKING_TIMEOUT
    from gateway.db.repositories import SubAgentRepository
    
    db = get_db()
    repo = SubAgentRepository(db)
    count = repo.reset_stuck_awaking(timeout_seconds)
    
    return {"reset_count": count}
