"""
Internal API module: helpers

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

import httpx

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db

# ==================== SubAgent Resolution Helper (Gateway Business APIs) ====================
# Gateway does NOT understand runtime; use subagent_id-only resolution for business endpoints.
# Resolution is done via RO API (RO owns subagent data); Gateway does NOT query local DB.


def resolve_agent_id_from_subagent(subagent_id: str) -> str:
    """
    Resolve agent_id from subagent_id via RO internal API (no local DB lookup).
    
    For Gateway business APIs that accept subagent_id-only input.
    Gateway must not perform runtime lookup logic or read subagent table locally.
    
    Args:
        subagent_id: SubAgent ID (globally unique)
    
    Returns:
        agent_id: Agent that owns this SubAgent
    
    Raises:
        HTTPException: If subagent not found (404 from RO) or RO unavailable
    """
    from gateway.clients.runtime_orchestrator import RuntimeOrchestratorClient

    if not RuntimeOrchestratorClient.is_enabled():
        raise HTTPException(
            status_code=500,
            detail="Runtime Orchestrator URL is not configured; subagent resolution requires RO",
        )

    base_url = ServiceConfig.RUNTIME_ORCHESTRATOR_URL.rstrip("/")
    path = f"/internal/subagents/by-id/{subagent_id}"
    try:
        from common.http.clients import internal_client

        with internal_client(
            base_url=base_url,
            timeout=getattr(ServiceConfig, "HTTP_TIMEOUT", 30.0),
        ) as client:
            response = client.get(path)
            response.raise_for_status()
            result = response.json()
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        detail = str(e)
        try:
            body = e.response.json()
            if isinstance(body, dict) and "detail" in body:
                detail = body["detail"] if isinstance(body["detail"], str) else str(body["detail"])
        except Exception:
            if e.response.text:
                detail = e.response.text[:500]
        raise HTTPException(status_code=status_code, detail=detail)
    except httpx.RequestError as e:
        raise HTTPException(
            status_code=502,
            detail=f"Failed to reach Runtime Orchestrator for subagent resolution: {e}",
        )

    agent_id = result.get("agent_id")
    if not agent_id:
        raise HTTPException(
            status_code=502,
            detail="Invalid response from RO: missing agent_id",
        )
    return agent_id


# ==================== Runtime Resolution Helper ====================
# NOTE: resolve_runtime_ids uses Runtime table lookup; do NOT use in Gateway business handlers.
# Kept for runtime-state APIs (/internal/runtimes*) and Runtime Orchestrator only.

def resolve_runtime_ids(runtime_id: str) -> Tuple[str, str, str]:
    """
    Resolve agent_id and subagent_id from runtime_id.
    
    This is the core of "runtime-first" API design:
    - MCP tools only need to pass runtime_id
    - agent_id and subagent_id are resolved from database
    
    Args:
        runtime_id: Runtime ID (rt-xxx)
    
    Returns:
        Tuple of (runtime_id, agent_id, subagent_id)
    
    Raises:
        HTTPException: If runtime not found
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail=f"Runtime not found: {runtime_id}")
    
    return runtime.runtime_id, runtime.agent_id, runtime.subagent_id


def get_runtime_context(runtime_id: str) -> Dict[str, Any]:
    """
    Get full runtime context including agent_id, subagent_id, and runtime details.
    
    Args:
        runtime_id: Runtime ID (rt-xxx)
    
    Returns:
        Dict with runtime_id, agent_id, subagent_id, status, etc.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail=f"Runtime not found: {runtime_id}")
    
    return {
        "runtime_id": runtime.runtime_id,
        "agent_id": runtime.agent_id,
        "subagent_id": runtime.subagent_id,
        "status": runtime.status,
        "phase": runtime.phase,
        "mcp_url": runtime.mcp_url,
    }



# ==================== Helpers ====================

def _runtime_to_dict(runtime) -> Dict[str, Any]:
    """Convert runtime to dictionary (v14 schema + v25 tool_ports)."""
    return {
        "runtime_id": runtime.runtime_id,
        "subagent_id": runtime.subagent_id,
        "agent_id": runtime.agent_id,
        "mcp_url": runtime.mcp_url,
        "current_round_id": runtime.current_round_id,
        "current_round_num": runtime.current_round_num,
        "phase": runtime.phase,
        "context": runtime.context,
        "pending_actions": runtime.pending_actions,
        "status": runtime.status,
        "error": runtime.error,
        "summary": runtime.summary,
        "need_rest": getattr(runtime, "need_rest", None),
        "summarized": getattr(runtime, "summarized", None),
        "is_merged": runtime.is_merged,
        "tool_ports": getattr(runtime, "tool_ports", None),
        "created_at": runtime.created_at,
        "updated_at": runtime.updated_at,
    }


def _subagent_to_dict(subagent) -> Dict[str, Any]:
    """Convert SubAgent to dictionary (v14)."""
    return {
        "subagent_id": subagent.subagent_id,
        "agent_id": subagent.agent_id,
        "type": subagent.type,
        "parent_subagent_id": subagent.parent_subagent_id,
        "status": subagent.status,
        "historical_summary": subagent.historical_summary,
        "wake_triggers": subagent.wake_triggers,
        "handoff_notes": subagent.handoff_notes,
        "created_at": subagent.created_at,
        "updated_at": subagent.updated_at,
    }

# ==================== Phase 4 Runtime Orchestrator Proxy ====================

_RUNTIME_ORCHESTRATOR_PROCESS = False
# Only /internal/runtimes and /internal/runtimes/* are forwarded to RO.
# /internal/subagents* moved to RO (RO owns them); Gateway no longer exposes them.
# /internal/rt, /internal/vm, /internal/messages stay in Gateway.
_RO_FORWARDED_PREFIX = "/internal/runtimes"


def set_runtime_orchestrator_process(is_runtime_orchestrator: bool) -> None:
    """Mark current process role to avoid self-proxy recursion."""
    global _RUNTIME_ORCHESTRATOR_PROCESS
    _RUNTIME_ORCHESTRATOR_PROCESS = is_runtime_orchestrator


async def maybe_forward_to_runtime_orchestrator(
    method: str,
    path: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    json_body: Optional[Dict[str, Any]] = None,
) -> Optional[Dict[str, Any]]:
    """
    If RUNTIME_ORCHESTRATOR_URL is set, forward the request and return the JSON response.
    Otherwise return None (caller should use local behavior).

    On proxy HTTP error, raises HTTPException with same status_code and detail.
    """
    from gateway.clients.runtime_orchestrator import (
        RuntimeOrchestratorClient,
        get_runtime_orchestrator_client,
    )

    # In Runtime Orchestrator process itself, always execute local handlers.
    # Otherwise requests would proxy to itself and recurse forever.
    if _RUNTIME_ORCHESTRATOR_PROCESS:
        return None

    # Forward only /internal/runtimes and /internal/runtimes/* to RO.
    # /internal/subagents* moved to RO. Business-domain (/internal/rt, /internal/vm, /internal/messages) stay in Gateway.
    if path != _RO_FORWARDED_PREFIX and not path.startswith(_RO_FORWARDED_PREFIX + "/"):
        return None

    if not RuntimeOrchestratorClient.is_enabled():
        raise HTTPException(
            status_code=500,
            detail="Runtime Orchestrator URL is not configured; Gateway requires it for internal API forwarding",
        )

    client = get_runtime_orchestrator_client()
    try:
        result = await client.forward(method, path, params=params, json=json_body)
        return result
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        detail = str(e)
        try:
            body = e.response.json()
            if isinstance(body, dict) and "detail" in body:
                detail = body["detail"] if isinstance(body["detail"], str) else str(body["detail"])
        except Exception:
            if e.response.text:
                detail = e.response.text[:500]
        raise HTTPException(status_code=status_code, detail=detail)


# Exported functions
__all__ = [
    "resolve_agent_id_from_subagent",
    "resolve_runtime_ids",
    "get_runtime_context",
    "_runtime_to_dict",
    "_subagent_to_dict",
    "set_runtime_orchestrator_process",
    "maybe_forward_to_runtime_orchestrator",
]
