"""
Internal API module: helpers

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db

# ==================== Runtime Resolution Helper ====================

def resolve_runtime_ids(runtime_id: str) -> Tuple[str, str, str]:
    """
    Resolve agent_id and subagent_id from runtime_id.
    
    This is the core of "runtime-first" API design:
    - MCP tools only need to pass runtime_id
    - agent_id and subagent_id are resolved from database
    
    Args:
        runtime_id: Runtime ID (rt-xxx)
    
    Returns:
        Tuple of (runtime_id, agent_id, subagent_id)
    
    Raises:
        HTTPException: If runtime not found
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail=f"Runtime not found: {runtime_id}")
    
    return runtime.runtime_id, runtime.agent_id, runtime.subagent_id


def get_runtime_context(runtime_id: str) -> Dict[str, Any]:
    """
    Get full runtime context including agent_id, subagent_id, and runtime details.
    
    Args:
        runtime_id: Runtime ID (rt-xxx)
    
    Returns:
        Dict with runtime_id, agent_id, subagent_id, status, etc.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail=f"Runtime not found: {runtime_id}")
    
    return {
        "runtime_id": runtime.runtime_id,
        "agent_id": runtime.agent_id,
        "subagent_id": runtime.subagent_id,
        "status": runtime.status,
        "phase": runtime.phase,
        "mcp_url": runtime.mcp_url,
    }



# ==================== Helpers ====================

def _runtime_to_dict(runtime) -> Dict[str, Any]:
    """Convert runtime to dictionary (v14 schema + v25 tool_ports)."""
    return {
        "runtime_id": runtime.runtime_id,
        "subagent_id": runtime.subagent_id,
        "agent_id": runtime.agent_id,
        "mcp_url": runtime.mcp_url,
        "current_round_id": runtime.current_round_id,
        "current_round_num": runtime.current_round_num,
        "phase": runtime.phase,
        "context": runtime.context,
        "pending_actions": runtime.pending_actions,
        "status": runtime.status,
        "error": runtime.error,
        "summary": runtime.summary,
        "need_rest": getattr(runtime, "need_rest", None),
        "summarized": getattr(runtime, "summarized", None),
        "is_merged": runtime.is_merged,
        "tool_ports": getattr(runtime, "tool_ports", None),
        "created_at": runtime.created_at,
        "updated_at": runtime.updated_at,
    }


def _subagent_to_dict(subagent) -> Dict[str, Any]:
    """Convert SubAgent to dictionary (v14)."""
    return {
        "subagent_id": subagent.subagent_id,
        "agent_id": subagent.agent_id,
        "type": subagent.type,
        "parent_subagent_id": subagent.parent_subagent_id,
        "status": subagent.status,
        "historical_summary": subagent.historical_summary,
        "wake_triggers": subagent.wake_triggers,
        "handoff_notes": subagent.handoff_notes,
        "created_at": subagent.created_at,
        "updated_at": subagent.updated_at,
    }

# Exported functions
__all__ = ['resolve_runtime_ids', 'get_runtime_context', '_runtime_to_dict', '_subagent_to_dict']
