"""
Internal API module: llm

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json
import time

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])


# ==================== Debug LLM Call ====================

class DebugLLMRequest(BaseModel):
    """调试 LLM 调用请求"""
    messages: List[Dict[str, Any]]  # 消息列表
    model: str  # 模型名称（必填）
    tools: Optional[List[Dict[str, Any]]] = None  # 工具定义
    provider: Optional[str] = "openai"  # provider，默认 openai
    preprocess: bool = True  # 是否预处理 messages（sanitize + multimodal）
    llm_config_id: Optional[str] = None  # 可选：指定 LLM 配置 ID


@router.post("/debug/llm/call")
def debug_llm_call(request: DebugLLMRequest):
    """
    调试用 LLM 调用
    
    特点：
    - 不写入 context
    - 不执行 tool_calls
    - 不触发 saga
    - 只返回 LLM 原始响应
    
    用于在 UI 中修改请求参数后重新发送，验证 LLM 行为。
    """
    from gateway.db.repositories import ConfigRepository
    from gateway.core.llm_client import OpenAIClient, AnthropicClient, GoogleAIClient
    
    db = get_db()
    config_repo = ConfigRepository(db)
    
    start_time = time.time()
    
    try:
        # 1. 获取 LLM 配置
        # 使用 get_model_config 根据 model_id 获取配置（含 API key）
        model_config = config_repo.get_model_config(request.model)
        
        if not model_config:
            # 如果找不到模型配置，尝试使用第一个 API key
            first_key = config_repo.get_first_api_key()
            if not first_key:
                return {
                    "success": False,
                    "error": f"Model '{request.model}' not found and no API key configured. Please configure an API key in Settings.",
                    "elapsed_ms": int((time.time() - start_time) * 1000),
                }
            model_config = {
                "api_key": first_key.get("api_key"),
                "api_base": first_key.get("api_base"),
                "provider": request.provider or "openai",
            }
        
        # 提取配置
        api_key = model_config.get("api_key")
        api_base = model_config.get("api_base") or "https://api.openai.com/v1"
        model = request.model
        # provider 优先使用请求中的，其次用 key_provider（API key 的 provider），最后用 model 的 provider
        provider = request.provider or model_config.get("key_provider") or model_config.get("provider") or "openai"
        
        # 2. 预处理 messages（可选）
        messages = request.messages
        if request.preprocess:
            try:
                from gateway.core.message_context import (
                    process_multimodal_messages,
                    sanitize_context,
                )
                messages = sanitize_context(messages)
                messages = process_multimodal_messages(messages, provider)
            except Exception as e:
                print(f"[debug/llm] Preprocess warning: {e}")
                # 预处理失败不阻塞，使用原始 messages
        
        # 3. 创建 LLM client
        if provider == "anthropic":
            llm_client = AnthropicClient(api_key=api_key, api_base=api_base)
        elif provider == "google":
            llm_client = GoogleAIClient(api_key=api_key, api_base=api_base)
        else:
            llm_client = OpenAIClient(api_base=api_base, api_key=api_key)
        
        # 4. 调用 LLM
        response = llm_client.chat(
            messages=messages,
            model=model,
            tools=request.tools,
        )
        
        elapsed_ms = int((time.time() - start_time) * 1000)
        
        # 5. 提取响应信息
        message = response.get("choices", [{}])[0].get("message", {})
        usage = response.get("usage", {})
        
        return {
            "success": True,
            "elapsed_ms": elapsed_ms,
            "model": model,
            "provider": provider,
            "response": {
                "content": message.get("content"),
                "reasoning_content": message.get("reasoning_content"),  # Kimi 等模型的推理内容
                "tool_calls": message.get("tool_calls"),
                "role": message.get("role", "assistant"),
            },
            "usage": {
                "prompt_tokens": usage.get("prompt_tokens", 0),
                "completion_tokens": usage.get("completion_tokens", 0),
                "total_tokens": usage.get("total_tokens", 0),
            },
            "raw_response": response,  # 完整原始响应，用于调试
        }
        
    except Exception as e:
        elapsed_ms = int((time.time() - start_time) * 1000)
        import traceback
        return {
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "elapsed_ms": elapsed_ms,
        }

# ==================== LLM Operations ====================

@router.post("/llm/compact-context")
def compact_context_with_llm(data: Dict[str, Any]):
    """
    Compact context using LLM.
    
    This endpoint calls an LLM to generate a summary of older messages.
    Used by Master's Scheduler for context compaction.
    """
    from gateway.config.settings import get_context_compaction_settings
    
    messages_to_compact = data.get("messages", [])
    agent_id = data.get("agent_id")
    
    if not messages_to_compact:
        return {"success": True, "summary": ""}
    
    # Get compaction settings
    settings = get_context_compaction_settings()
    
    # Get API configuration from database
    from gateway.db.repositories import ConfigRepository
    
    db = get_db()
    config_repo = ConfigRepository(db)
    
    # Get first API key from api_keys table
    row = config_repo.get_first_api_key()
    if not row:
        return {"success": False, "error": "No API keys configured"}
    
    api_key = row["api_key"]
    base_url = row["api_base"] or "https://api.openai.com/v1"
    
    # Use compaction model from settings
    model = settings.compaction_model
    
    # Format messages for compaction
    messages_text = "\n".join([
        f"[{m.get('role', 'unknown')}]: {m.get('content', '')[:ServiceConfig.TEXT_TRUNCATE_MESSAGE]}"
        for m in messages_to_compact
    ])
    
    # Build LLM request
    llm_messages = [
        {"role": "system", "content": settings.compaction_prompt},
        {"role": "user", "content": f"请压缩以下对话历史：\n\n{messages_text}"}
    ]
    
    try:
        from common.http.clients import external_client
        with external_client(timeout=ServiceConfig.LLM_CALL_TIMEOUT) as client:
            response = client.post(
                f"{base_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": model,
                    "messages": llm_messages,
                    "temperature": ServiceConfig.LLM_TEMPERATURE_DEFAULT,
                    "max_tokens": ServiceConfig.LLM_MAX_TOKENS_DEFAULT,
                }
            )
            response.raise_for_status()
            result = response.json()
            
            summary = result.get("choices", [{}])[0].get("message", {}).get("content", "")
            
            return {
                "success": True,
                "summary": summary,
                "compacted_count": len(messages_to_compact),
            }
    except Exception as e:
        print(f"[Internal] LLM compaction failed: {e}")
        return {"success": False, "error": str(e)}
