"""
Internal API module: message

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.utils.time import utc_now_iso
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Message Operations ====================

@router.get("/messages/unread/{agent_id}")
def get_unread_messages(agent_id: str):
    """Get unread messages for an agent (for Scheduler to include in context).
    
    Uses read=0 to find messages that haven't been processed yet.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    messages = repo.get_unread(agent_id)
    
    # Filter for USER_MESSAGE type only (matching original behavior)
    user_messages = [m for m in messages if m.get("type") == "USER_MESSAGE"]
    
    return {"messages": user_messages}


def _parse_message_content(content) -> dict:
    """Parse stored content: JSON {"text","attachments"} or plain string -> dict."""
    if content is None:
        return {"text": "", "attachments": []}
    if isinstance(content, dict):
        return content
    s = str(content).strip()
    if not s:
        return {"text": "", "attachments": []}
    if s.startswith("{") and "attachments" in s:
        try:
            return json.loads(s)
        except json.JSONDecodeError:
            pass
    return {"text": s, "attachments": []}


@router.get("/messages/unread-sent/{agent_id}")
def get_unread_sent_messages(agent_id: str):
    """Get unread sent messages for an agent (USER_MESSAGE, SYSTEM_WAKE, SUBAGENT_COMPLETED)."""
    from gateway.db.repositories.message import MessageRepository

    db = get_db()
    repo = MessageRepository(db)
    messages = repo.get_unread(agent_id)
    
    # Include USER_MESSAGE, SYSTEM_WAKE, and SUBAGENT_COMPLETED types
    # All are treated as user role messages in the LLM context
    valid_types = ("USER_MESSAGE", "SYSTEM_WAKE", "SUBAGENT_COMPLETED")
    user_messages = []
    for m in messages:
        if m.get("type") not in valid_types:
            continue
        content = _parse_message_content(m["content"])
        user_messages.append({
            "id": m["id"],
            "content": content,
            "timestamp": m["timestamp"],
            "type": m.get("type"),
        })

    return {"messages": user_messages}


@router.get("/messages/unread-count/{agent_id}")
def get_unread_count(agent_id: str):
    """Get count of unread messages (for Monitor to detect new messages).
    
    Uses read=0 to find messages that haven't been processed yet.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    count = repo.get_unread_user_message_count(agent_id)
    
    return {"count": count}


@router.get("/messages/unread-grouped")
def get_unread_messages_grouped(agent_id: Optional[str] = None):
    """Get unread messages grouped by agent_id (v14 for Monitor).
    
    Returns all agents with unread USER_MESSAGE messages.
    Uses read=0 to find messages that haven't been processed yet.
    """
    
    db = get_db()
    
    # Get all unread messages with their agent_id
    rows = db.fetchall("""
        SELECT id, agent_id, type, content, metadata, timestamp 
        FROM chat_messages 
        WHERE read = 0 AND type = 'USER_MESSAGE'
        ORDER BY agent_id, timestamp ASC
    """)
    
    # Group by agent_id
    messages_by_agent: Dict[str, List[Dict[str, Any]]] = {}
    for row in rows:
        aid = row["agent_id"]
        if aid not in messages_by_agent:
            messages_by_agent[aid] = []
        messages_by_agent[aid].append({
            "id": row["id"],
            "type": row["type"],
            "content": row["content"],
            "metadata": json.loads(row["metadata"]) if row.get("metadata") else {},
            "timestamp": row["timestamp"],
        })
    
    return {"messages_by_agent": messages_by_agent}


@router.post("/messages/claim-and-prepare")
def claim_and_prepare_message():
    """Claim one sending message and prepare for processing.
    
    Used by Watchdog to:
    1. Find a sending message
    2. Claim it (sending → sent) atomically
    3. Return message info for saga creation
    
    Returns:
        {"message": {...}} if claimed, {"message": null} if queue is empty
        
    DEPRECATED: 使用 /messages/find-sending + /messages/{id}/confirm 两阶段提交替代
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    message = repo.claim_sending()
    
    return {"message": message}


@router.post("/messages/find-sending")
def find_sending_message():
    """Find one sending message without changing its status.
    
    两阶段提交第一阶段：
    1. 查找一条 sending 状态的消息
    2. 返回消息但不改变状态
    
    调用方需要：
    1. 先创建 Saga（幂等，使用 message_id 作为幂等键）
    2. Saga 创建成功后，调用 /messages/{id}/confirm 确认消息
    
    Returns:
        {"message": {...}} if found, {"message": null} if queue is empty
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    message = repo.find_sending()
    
    return {"message": message}


@router.post("/messages/{message_id}/confirm")
def confirm_message(message_id: str):
    """Confirm a message (sending → sent).
    
    两阶段提交第二阶段：
    Saga 创建成功后调用此方法确认消息。
    
    使用 CAS 保证幂等性：
    - 如果消息状态是 sending，更新为 sent
    - 如果消息已经是 sent，返回成功（幂等）
    
    Returns:
        {"success": bool, "message_id": str, "confirmed": bool}
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    confirmed = repo.confirm_message(message_id)
    
    if confirmed:
        return {"success": True, "message_id": message_id, "confirmed": True}
    
    # 检查当前状态，判断是否已经确认（幂等）
    msg = repo.get_message(message_id)
    current_status = msg["status"] if msg else "not_found"
    
    return {
        "success": current_status == "sent",  # 如果已经是 sent，视为成功
        "message_id": message_id,
        "confirmed": False,
        "current_status": current_status,
    }


@router.post("/messages/{message_id}/claim")
def claim_message(message_id: str):
    """
    Claim a message (sending -> sent) with CAS.
    
    Uses FIFO lock (sharded by message_id) to ensure fair ordering.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    claimed = repo.claim_by_id(message_id)
    
    if claimed:
        return {"success": True, "message_id": message_id, "claimed": True}

    # Check current status using repository
    msg = repo.get_message(message_id)
    current_status = msg["status"] if msg else "not_found"
    return {
        "success": current_status == "sent",
        "message_id": message_id,
        "claimed": False,
        "current_status": current_status,
    }


@router.get("/messages/has-new/{agent_id}")
def has_new_messages(agent_id: str):
    """Check if agent has new sent unread user messages."""
    from gateway.db.repositories.message import MessageRepository

    db = get_db()
    repo = MessageRepository(db)
    count = repo.get_pending_count(agent_id)
    
    return {"has_new_messages": count > 0}


@router.patch("/messages/mark-read")
def mark_messages_read(data: Dict[str, Any]):
    """Mark messages as read and broadcast status update."""
    import uuid as uuid_module
    from gateway.db.repositories.message import MessageRepository
    
    message_ids = data.get("message_ids", [])
    agent_id = data.get("agent_id")  # Optional: for SSE filtering
    
    if not message_ids:
        return {"status": "ok"}
    
    db = get_db()
    repo = MessageRepository(db)
    
    # If no agent_id provided, try to get it from the first message
    if not agent_id:
        msg = repo.get_message(message_ids[0])
        if msg:
            agent_id = msg["agent_id"]
    
    # Batch mark as read
    repo.batch_mark_read(message_ids, agent_id)
    
    # Broadcast STATUS_UPDATE to SSE for each message
    try:
        from main_gateway import _chat_subscribers
        for msg_id in message_ids:
            status_update = {
                "id": str(uuid_module.uuid4())[:8],
                "type": "STATUS_UPDATE",
                "message_id": msg_id,
                "status": "read",
                "agent_id": agent_id,  # Include agent_id for SSE filtering
                "timestamp": utc_now_iso(),
            }
            for queue in _chat_subscribers.values():
                try:
                    queue.put_nowait(status_update)
                except:
                    pass
    except Exception as e:
        print(f"[Internal] Failed to broadcast status update: {e}")
    
    return {"status": "ok"}


@router.patch("/messages/mark-processed")
def mark_messages_processed(data: Dict[str, Any]):
    """Mark messages as read and broadcast status update to SSE.
    
    Note: 'processed' concept is merged into 'read'. Once read=1, message is considered processed.
    """
    import uuid as uuid_module
    from gateway.db.repositories.message import MessageRepository
    
    message_ids = data.get("message_ids", [])
    agent_id = data.get("agent_id")  # Optional: for SSE filtering
    
    if not message_ids:
        return {"status": "ok"}
    
    db = get_db()
    repo = MessageRepository(db)
    
    # If no agent_id provided, try to get it from the first message
    if not agent_id:
        msg = repo.get_message(message_ids[0])
        if msg:
            agent_id = msg["agent_id"]
    
    # Batch mark as read (read=1 means processed)
    repo.batch_mark_read(message_ids, agent_id)
    
    # Broadcast STATUS_UPDATE to SSE for each message
    # Import here to avoid circular import
    try:
        from main_gateway import _chat_subscribers
        for msg_id in message_ids:
            status_update = {
                "id": str(uuid_module.uuid4())[:8],
                "type": "STATUS_UPDATE",
                "message_id": msg_id,
                "status": "read",
                "agent_id": agent_id,  # Include agent_id for SSE filtering
                "timestamp": utc_now_iso(),
            }
            for queue in _chat_subscribers.values():
                try:
                    queue.put_nowait(status_update)
                except:
                    pass
    except Exception as e:
        print(f"[Internal] Failed to broadcast status update: {e}")
    
    return {"status": "ok"}


@router.post("/messages/inject-subagent-completed")
def inject_subagent_completed_message(data: Dict[str, Any]):
    """Inject a SUBAGENT_COMPLETED message to notify parent SubAgent.
    
    Used by RuntimeComplete Saga to notify Main SubAgent when a Sub SubAgent
    completes its task. The message will be picked up by Watchdog and either:
    - Read by ReactThink if Main is running
    - Trigger wake-up if Main is sleeping
    
    Args:
        data: {
            "agent_id": str - Agent ID
            "subagent_id": str - Completed Sub SubAgent ID
            "parent_subagent_id": str - Target SubAgent to notify
            "result": str - Task result summary (optional)
        }
    """
    from gateway.db.repositories.message import MessageRepository
    from gateway.db.repositories.subagent import SubAgentRepository
    
    db = get_db()
    message_repo = MessageRepository(db)
    subagent_repo = SubAgentRepository(db)
    
    agent_id = data.get("agent_id")
    subagent_id = data.get("subagent_id")
    parent_subagent_id = data.get("parent_subagent_id")
    result = data.get("result", "")
    
    if not agent_id:
        return {"success": False, "error": "agent_id is required"}
    if not subagent_id:
        return {"success": False, "error": "subagent_id is required"}
    
    # 如果没有指定 parent，尝试从 SubAgent 记录获取，否则默认 main
    if not parent_subagent_id:
        subagent = subagent_repo.get_by_id(subagent_id, agent_id)
        if subagent and subagent.parent_subagent_id:
            parent_subagent_id = subagent.parent_subagent_id
        else:
            parent_subagent_id = f"main-{agent_id[:8]}"
    
    # 构建消息内容
    result_summary = result[:500] + "..." if len(result) > 500 else result
    content = f"[子任务完成通知]\n\n子任务 {subagent_id} 已完成。"
    if result_summary:
        content += f"\n\n结果摘要:\n{result_summary}"
    
    # 创建消息，status=sending 会被 Watchdog 监测
    msg = message_repo.add_message(
        agent_id=agent_id,
        type="SUBAGENT_COMPLETED",
        content=content,
        metadata={
            "subagent_id": subagent_id,
            "parent_subagent_id": parent_subagent_id,
            "result": result,
        },
        status="sending",  # Watchdog will process this
    )
    
    return {
        "success": True,
        "message_id": msg["id"],
        "agent_id": agent_id,
        "subagent_id": subagent_id,
        "parent_subagent_id": parent_subagent_id,
    }


@router.post("/messages/inject-wake")
def inject_wake_message(data: Dict[str, Any]):
    """Inject a SYSTEM_WAKE message to trigger agent wake-up.
    
    Used by SchedulerWorker to wake sleeping agents via the normal
    Watchdog -> MessageProcess flow.
    
    The message content is dynamically generated with wake context
    (time, last interaction, active hours, etc.)
    
    Args:
        data: {
            "agent_id": str - Agent to wake
            "metadata": dict - Wake metadata (wake_reason, handoff_notes, etc.)
        }
    """
    from gateway.db.repositories.message import MessageRepository
    from task_queue.client import GatewayInternalClient
    from task_queue.utils.system_prompt import build_wake_message
    
    db = get_db()
    repo = MessageRepository(db)
    
    agent_id = data.get("agent_id")
    if not agent_id:
        return {"success": False, "error": "agent_id is required"}
    
    metadata = data.get("metadata", {})
    
    # 生成完整的 wake message 内容
    try:
        client = GatewayInternalClient(ServiceConfig.GATEWAY_URL)
        wake_content = build_wake_message(agent_id, client)
        client.close()
    except Exception as e:
        # 降级到简单消息
        print(f"[inject_wake] Failed to build wake message: {e}")
        wake_content = "[系统定时唤醒]\n\n请检查任务看板和笔记本，决定是否需要联系用户。"
    
    msg = repo.add_message(
        agent_id=agent_id,
        type="SYSTEM_WAKE",
        content=wake_content,
        metadata=metadata,
        status="sending",  # Watchdog will claim this
    )
    
    return {
        "success": True,
        "message_id": msg["id"],
        "agent_id": agent_id,
    }


@router.post("/messages")
def create_message(data: Dict[str, Any]):
    """Create a chat message.
    
    - USER_MESSAGE, SYSTEM_WAKE, SPAWN_SUBAGENT, SUBAGENT_COMPLETED: 
      Use status='sending' so Watchdog can detect and process them.
    - AGENT_REPLY, AGENT_ASK, etc.: 
      Use status='sent' directly (no Watchdog processing needed).
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    # 需要 Watchdog 处理的消息类型
    watchdog_types = {"USER_MESSAGE", "SYSTEM_WAKE", "SPAWN_SUBAGENT", "SUBAGENT_COMPLETED"}
    msg_type = data.get("type", "")
    
    # 根据消息类型决定初始状态
    initial_status = "sending" if msg_type in watchdog_types else "sent"
    
    msg = repo.add_message(
        agent_id=data["agent_id"],
        type=data["type"],
        content=data["content"],
        metadata=data.get("metadata"),
        status=initial_status,
    )
    
    return msg
