"""
Internal API module: message

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Message Operations ====================

@router.get("/messages/unread/{agent_id}")
def get_unread_messages(agent_id: str):
    """Get unread messages for an agent (for Scheduler to include in context).
    
    Uses read=0 to find messages that haven't been processed yet.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    messages = repo.get_unread(agent_id)
    
    # Filter for USER_MESSAGE type only (matching original behavior)
    user_messages = [m for m in messages if m.get("type") == "USER_MESSAGE"]
    
    return {"messages": user_messages}


@router.get("/messages/unread-sent/{agent_id}")
def get_unread_sent_messages(agent_id: str):
    """Get unread sent user messages for an agent."""
    from gateway.db.repositories.message import MessageRepository

    db = get_db()
    repo = MessageRepository(db)
    messages = repo.get_unread(agent_id)
    
    # Filter for USER_MESSAGE type only (matching original behavior)
    user_messages = [
        {"id": m["id"], "content": m["content"], "timestamp": m["timestamp"]}
        for m in messages if m.get("type") == "USER_MESSAGE"
    ]

    return {"messages": user_messages}


@router.get("/messages/unread-count/{agent_id}")
def get_unread_count(agent_id: str):
    """Get count of unread messages (for Monitor to detect new messages).
    
    Uses read=0 to find messages that haven't been processed yet.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    count = repo.get_unread_user_message_count(agent_id)
    
    return {"count": count}


@router.get("/messages/unread-grouped")
def get_unread_messages_grouped(agent_id: Optional[str] = None):
    """Get unread messages grouped by agent_id (v14 for Monitor).
    
    Returns all agents with unread USER_MESSAGE messages.
    Uses read=0 to find messages that haven't been processed yet.
    """
    
    db = get_db()
    
    # Get all unread messages with their agent_id
    rows = db.fetchall("""
        SELECT id, agent_id, type, content, metadata, timestamp 
        FROM chat_messages 
        WHERE read = 0 AND type = 'USER_MESSAGE'
        ORDER BY agent_id, timestamp ASC
    """)
    
    # Group by agent_id
    messages_by_agent: Dict[str, List[Dict[str, Any]]] = {}
    for row in rows:
        aid = row["agent_id"]
        if aid not in messages_by_agent:
            messages_by_agent[aid] = []
        messages_by_agent[aid].append({
            "id": row["id"],
            "type": row["type"],
            "content": row["content"],
            "metadata": json.loads(row["metadata"]) if row.get("metadata") else {},
            "timestamp": row["timestamp"],
        })
    
    return {"messages_by_agent": messages_by_agent}


@router.post("/messages/claim-and-prepare")
def claim_and_prepare_message():
    """Claim one sending message and prepare for processing.
    
    Used by Watchdog to:
    1. Find a sending message
    2. Claim it (sending → sent) atomically
    3. Return message info for saga creation
    
    Returns:
        {"message": {...}} if claimed, {"message": null} if queue is empty
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    message = repo.claim_sending()
    
    return {"message": message}


@router.post("/messages/{message_id}/claim")
def claim_message(message_id: str):
    """
    Claim a message (sending -> sent) with CAS.
    
    Uses FIFO lock (sharded by message_id) to ensure fair ordering.
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    claimed = repo.claim_by_id(message_id)
    
    if claimed:
        return {"success": True, "message_id": message_id, "claimed": True}

    # Check current status using repository
    msg = repo.get_message(message_id)
    current_status = msg["status"] if msg else "not_found"
    return {
        "success": current_status == "sent",
        "message_id": message_id,
        "claimed": False,
        "current_status": current_status,
    }


@router.get("/messages/has-new/{agent_id}")
def has_new_messages(agent_id: str):
    """Check if agent has new sent unread user messages."""
    from gateway.db.repositories.message import MessageRepository

    db = get_db()
    repo = MessageRepository(db)
    count = repo.get_pending_count(agent_id)
    
    return {"has_new_messages": count > 0}


@router.patch("/messages/mark-read")
def mark_messages_read(data: Dict[str, Any]):
    """Mark messages as read and broadcast status update."""
    from datetime import datetime
    import uuid as uuid_module
    from gateway.db.repositories.message import MessageRepository
    
    message_ids = data.get("message_ids", [])
    agent_id = data.get("agent_id")  # Optional: for SSE filtering
    
    if not message_ids:
        return {"status": "ok"}
    
    db = get_db()
    repo = MessageRepository(db)
    
    # If no agent_id provided, try to get it from the first message
    if not agent_id:
        msg = repo.get_message(message_ids[0])
        if msg:
            agent_id = msg["agent_id"]
    
    # Batch mark as read
    repo.batch_mark_read(message_ids, agent_id)
    
    # Broadcast STATUS_UPDATE to SSE for each message
    try:
        from main_gateway import _chat_subscribers
        for msg_id in message_ids:
            status_update = {
                "id": str(uuid_module.uuid4())[:8],
                "type": "STATUS_UPDATE",
                "message_id": msg_id,
                "status": "read",
                "agent_id": agent_id,  # Include agent_id for SSE filtering
                "timestamp": datetime.utcnow().isoformat(),
            }
            for queue in _chat_subscribers.values():
                try:
                    queue.put_nowait(status_update)
                except:
                    pass
    except Exception as e:
        print(f"[Internal] Failed to broadcast status update: {e}")
    
    return {"status": "ok"}


@router.patch("/messages/mark-processed")
def mark_messages_processed(data: Dict[str, Any]):
    """Mark messages as read and broadcast status update to SSE.
    
    Note: 'processed' concept is merged into 'read'. Once read=1, message is considered processed.
    """
    from datetime import datetime
    import uuid as uuid_module
    from gateway.db.repositories.message import MessageRepository
    
    message_ids = data.get("message_ids", [])
    agent_id = data.get("agent_id")  # Optional: for SSE filtering
    
    if not message_ids:
        return {"status": "ok"}
    
    db = get_db()
    repo = MessageRepository(db)
    
    # If no agent_id provided, try to get it from the first message
    if not agent_id:
        msg = repo.get_message(message_ids[0])
        if msg:
            agent_id = msg["agent_id"]
    
    # Batch mark as read (read=1 means processed)
    repo.batch_mark_read(message_ids, agent_id)
    
    # Broadcast STATUS_UPDATE to SSE for each message
    # Import here to avoid circular import
    try:
        from main_gateway import _chat_subscribers
        for msg_id in message_ids:
            status_update = {
                "id": str(uuid_module.uuid4())[:8],
                "type": "STATUS_UPDATE",
                "message_id": msg_id,
                "status": "read",
                "agent_id": agent_id,  # Include agent_id for SSE filtering
                "timestamp": datetime.utcnow().isoformat(),
            }
            for queue in _chat_subscribers.values():
                try:
                    queue.put_nowait(status_update)
                except:
                    pass
    except Exception as e:
        print(f"[Internal] Failed to broadcast status update: {e}")
    
    return {"status": "ok"}


@router.post("/messages/inject-wake")
def inject_wake_message(data: Dict[str, Any]):
    """Inject a SYSTEM_WAKE message to trigger agent wake-up.
    
    Used by SchedulerWorker to wake sleeping agents via the normal
    Watchdog -> MessageProcess flow.
    
    Args:
        data: {
            "agent_id": str - Agent to wake
            "metadata": dict - Wake metadata (wake_reason, handoff_notes, etc.)
        }
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    agent_id = data.get("agent_id")
    if not agent_id:
        return {"success": False, "error": "agent_id is required"}
    
    metadata = data.get("metadata", {})
    
    msg = repo.add_message(
        agent_id=agent_id,
        type="SYSTEM_WAKE",
        content="[Scheduled wake]",
        metadata=metadata,
        status="sending",  # Watchdog will claim this
    )
    
    return {
        "success": True,
        "message_id": msg["id"],
        "agent_id": agent_id,
    }


@router.post("/messages")
def create_message(data: Dict[str, Any]):
    """Create a chat message (for agent replies).
    
    Agent replies use status='sent' directly (no Monitor processing needed).
    """
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    
    msg = repo.add_message(
        agent_id=data["agent_id"],
        type=data["type"],
        content=data["content"],
        metadata=data.get("metadata"),
        status="sent",  # v18: Agent replies skip Monitor queue
    )
    
    return msg
