"""
Internal API module: runtime

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime, timedelta
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.utils.time import utc_now, utc_now_iso
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Runtime Operations ====================

@router.get("/runtimes/active")
def get_active_runtimes():
    """Get all active runtimes."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtimes = repo.get_all_active_runtimes()
    
    return {
        "runtimes": [_runtime_to_dict(r) for r in runtimes]
    }


@router.get("/runtimes/list")
def list_active_runtimes_for_mcp():
    """List all active runtimes.
    
    Used by Tools Server for runtime_list tool.
    NOTE: Must be defined BEFORE /runtimes/{runtime_id} to avoid route conflict.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtimes = runtime_repo.get_all_active_runtimes()
    
    return {
        "runtimes": [
            {
                "runtime_id": r.runtime_id,
                "agent_id": r.agent_id,
                "subagent_id": r.subagent_id,
                "type": "main" if r.subagent_id and r.subagent_id.startswith("main-") else "subagent",
                "status": r.status,
                "created_at": r.created_at,
            }
            for r in runtimes
        ]
    }


@router.post("/runtimes/batch")
def get_runtimes_batch(data: Dict[str, Any]):
    """Get multiple runtimes by IDs (for context building).
    
    Request body:
        runtime_ids: List[str] - List of runtime IDs to fetch
        
    Returns:
        runtimes: List of runtime dicts with summaries, in input order
    """
    from gateway.db.repositories import RuntimeRepository
    
    runtime_ids = data.get("runtime_ids", [])
    if not runtime_ids:
        return {"runtimes": []}
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtimes = repo.get_runtimes_by_ids(runtime_ids)
    
    # Convert to dict with summary fields
    result = []
    for rt in runtimes:
        result.append({
            "runtime_id": rt.runtime_id,
            "subagent_id": rt.subagent_id,
            "agent_id": rt.agent_id,
            "status": rt.status,
            "simple_summary": rt.simple_summary,
            "hot_summary": rt.hot_summary,
            "cold_summary": rt.cold_summary,
            "created_at": rt.created_at,
        })
    
    return {"runtimes": result}


@router.get("/runtimes/with-tools")
def get_runtimes_with_tools():
    """Get all active runtimes that have tool_ports registered.
    
    Used by Tools Server on startup to restore runtime tool contexts.
    Returns only runtimes with status = 'active' AND tool_ports IS NOT NULL.
    
    NOTE: Must be defined BEFORE /runtimes/{runtime_id} to avoid route conflict.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtimes = runtime_repo.get_all_active_runtimes()
    
    # Filter to only runtimes with tool_ports registered (including empty ports)
    result = []
    for r in runtimes:
        if r.tool_ports is not None:
            result.append({
                "runtime_id": r.runtime_id,
                "agent_id": r.agent_id,
                "subagent_id": r.subagent_id,
                "tool_ports": r.tool_ports,
                "created_at": r.created_at,
            })
    
    return {"runtimes": result, "total": len(result)}


@router.get("/runtimes/{runtime_id}")
def get_runtime(runtime_id: str):
    """Get a single runtime by ID."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtime = repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail="Runtime not found")
    
    return _runtime_to_dict(runtime)


@router.post("/runtimes")
def create_runtime(data: Dict[str, Any]):
    """Create a new Runtime for a SubAgent (v14)."""
    from gateway.db.repositories import RuntimeRepository
    
    agent_id = data.get("agent_id")
    subagent_id = data.get("subagent_id", "main")
    initial_context = data.get("initial_context", [])
    
    if not agent_id:
        raise HTTPException(status_code=400, detail="agent_id required")
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtime = repo.create_runtime(subagent_id, agent_id, initial_context)
    
    return _runtime_to_dict(runtime)


@router.post("/runtimes/get-or-create")
def get_or_create_runtime(data: Dict[str, Any]):
    """原子操作：获取或创建 active runtime。
    
    如果已有 active runtime，返回它；否则创建新的。
    用于替代 awaking 状态，保证同一时间只有一个 active runtime。
    
    Request body:
        agent_id: str - Agent ID
        subagent_id: str - SubAgent ID (default: "main")
        initial_context: List[Dict] - 新创建时的初始 context (optional)
        
    Returns:
        runtime: Runtime dict
        just_created: bool - 是否新创建的
    """
    from gateway.db.repositories import RuntimeRepository
    
    agent_id = data.get("agent_id")
    subagent_id = data.get("subagent_id", "main")
    initial_context = data.get("initial_context", [])
    
    if not agent_id:
        raise HTTPException(status_code=400, detail="agent_id required")
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtime, just_created = repo.get_or_create_active_runtime(
        subagent_id, agent_id, initial_context
    )
    
    result = _runtime_to_dict(runtime)
    result["just_created"] = just_created
    return result


@router.post("/runtimes/main")
def create_main_runtime(data: Dict[str, Any]):
    """Create a new Main Runtime (deprecated, use POST /runtimes)."""
    from gateway.db.repositories import RuntimeRepository, SubAgentRepository
    
    agent_id = data.get("agent_id")
    if not agent_id:
        raise HTTPException(status_code=400, detail="agent_id required")

    subagent_id = data.get("subagent_id")
    initial_context = data.get("initial_context", [])

    db = get_db()
    subagent_repo = SubAgentRepository(db)

    if subagent_id:
        subagent = subagent_repo.get_by_id(subagent_id, agent_id)
        if not subagent:
            raise HTTPException(status_code=404, detail="SubAgent not found")
    else:
        subagent = subagent_repo.get_or_create_main_subagent(agent_id)
        subagent_id = subagent.subagent_id

    repo = RuntimeRepository(db)
    runtime = repo.create_runtime(subagent_id, agent_id, initial_context)

    return _runtime_to_dict(runtime)


@router.patch("/runtimes/{runtime_id}")
def update_runtime(runtime_id: str, data: Dict[str, Any]):
    """Update runtime fields."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    
    # Handle specific updates
    if "phase" in data and "pending_actions" in data:
        repo.set_pending_actions(
            runtime_id, 
            data["pending_actions"], 
            data["phase"]
        )
    elif "phase" in data:
        repo.set_phase(runtime_id, data["phase"])
    
    if "context" in data:
        repo.update_context(runtime_id, data["context"])
    
    if "mcp_url" in data:
        repo.set_mcp_url(runtime_id, data["mcp_url"])
    
    if "status" in data:
        if data["status"] == RuntimeStatus.COMPLETED.value:
            repo.mark_completed(runtime_id)
        elif data["status"] == RuntimeStatus.FAILED.value:
            repo.mark_failed(runtime_id, data.get("error", "Unknown error"))
        elif data["status"] == RuntimeStatus.ACTIVE.value:
            repo.set_status(runtime_id, RuntimeStatus.ACTIVE.value)
    
    if "summary" in data:
        repo.set_summary(runtime_id, data["summary"])
    
    if "is_merged" in data and data["is_merged"]:
        repo.mark_merged(runtime_id)
    
    # Handle round updates
    if "current_round_num" in data and "current_round_id" in data:
        repo.reset_round(runtime_id, data["current_round_num"], data["current_round_id"])
    
    return {"status": "ok"}


@router.post("/runtimes/{runtime_id}/rest")
def rest_runtime(runtime_id: str, data: Dict[str, Any]):
    """
    Set runtime need_rest flag and update SubAgent wake triggers.
    
    Called by runtime_rest tool. Sets need_rest=1 on runtime and
    updates the SubAgent's wake_triggers for scheduled wake.
    
    Args:
        runtime_id: Runtime ID
        data: {
            "reason": str - Why the runtime needs rest
            "wake_triggers": list - Conditions to wake up
            "handoff_notes": str - Notes for next activation
        }
    """
    from gateway.db.repositories import RuntimeRepository, SubAgentRepository
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    subagent_repo = SubAgentRepository(db)
    
    # Check if runtime exists
    runtime = runtime_repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "error": "Runtime not found"}
    
    # Set need_rest=1 (不再设置 status='resting')
    runtime_repo.set_need_rest(runtime_id, True)
    
    # Update SubAgent's wake triggers and schedule (v26)
    reason = data.get("reason", "No reason provided")
    wake_triggers = data.get("wake_triggers", [{"type": "user_response"}])
    handoff_notes = data.get("handoff_notes")
    rest_duration = data.get("rest_duration_minutes", 30)
    rest_duration = max(1, min(1440, rest_duration))  # clamp 1min - 24h
    
    wake_at = (utc_now() + timedelta(minutes=rest_duration)).isoformat()
    
    subagent_repo.update_wake_info(
        runtime.subagent_id,
        runtime.agent_id,
        wake_triggers=wake_triggers,
        wake_at=wake_at,
        handoff_notes=handoff_notes,
    )
    
    return {
        "success": True,
        "state": "need_rest",
        "reason": reason,
        "triggers_set": len(wake_triggers),
        "estimated_wake": wake_at,
        "rest_duration_minutes": rest_duration,
        "handoff_notes": handoff_notes,
    }


@router.post("/runtimes/{runtime_id}/wake")
def wake_runtime(runtime_id: str):
    """Wake a sleeping runtime (deprecated in v14, use SubAgent wake).
    
    Returns success=True only if the runtime was actually woken up.
    Returns success=False if runtime was already active or not found.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    success = repo.wake_main_runtime(runtime_id)
    
    return {"status": "ok" if success else "skipped", "success": success}


@router.post("/runtimes/{runtime_id}/advance")
def advance_runtime_round(runtime_id: str, data: Dict[str, Any] = None):
    """Advance runtime to next round (with optional CAS).
    
    Args:
        data: Optional dict with 'expected_round_num' for CAS operation
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    
    expected_round_num = None
    if data:
        expected_round_num = data.get("expected_round_num")
    
    new_round_id = repo.advance_round(runtime_id, expected_round_num)
    
    if new_round_id is None:
        return {"round_id": None, "success": False, "reason": "CAS conflict or runtime not found"}
    
    return {"round_id": new_round_id, "success": True}


# DEPRECATED: /runtimes/{runtime_id}/claim-phase 已删除，Saga 步骤替代 phase 状态


@router.post("/runtimes/{runtime_id}/context/append")
def append_runtime_context(runtime_id: str, data: Dict[str, Any]):
    """Append a message to runtime context with idempotency."""
    from gateway.db.repositories import RuntimeRepository
    from task_queue.utils import multimodal

    message = data.get("message")
    # 检查 message 是否为 None 或空字典（空字典视为无效消息）
    if message is None:
        raise HTTPException(status_code=400, detail="message required")
    # 空字典 {} 也视为无效消息，但返回成功（幂等处理）
    if not message or (isinstance(message, dict) and not message.get("role") and not message.get("content")):
        return {
            "success": True,
            "appended": False,
            "context_length": 0,
            "message": "Empty message skipped",
        }

    message_type = data.get("message_type", "unknown")
    round_id = data.get("round_id")
    idempotency_key = data.get("idempotency_key")

    db = get_db()
    repo = RuntimeRepository(db)
    runtime = repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "error": "Runtime not found"}

    context = runtime.context or []
    if idempotency_key:
        for msg in context:
            if msg.get("_idempotency_key") == idempotency_key:
                return {
                    "success": True,
                    "appended": False,
                    "context_length": len(context),
                    "message": "Message already exists",
                }

    # 注意：不在这里处理图片分离！
    # 保持原始 tool result（包含完整图片数据）
    # 图片提取由 task_queue/utils/context.py:process_multimodal_messages 在 LLM 调用时处理

    message_with_meta = {
        **message,
        "_round_id": round_id,
        "_message_type": message_type,
    }
    if idempotency_key:
        message_with_meta["_idempotency_key"] = idempotency_key

    context.append(message_with_meta)
    repo.update_context(runtime_id, context)

    return {
        "success": True,
        "appended": True,
        "context_length": len(context),
    }


@router.post("/runtimes/{runtime_id}/set-status")
def set_runtime_status(runtime_id: str, data: Dict[str, Any]):
    """Set runtime status with CAS on expected status list."""
    from gateway.db.repositories import RuntimeRepository

    expected_status = data.get("expected_status")
    new_status = data.get("new_status")
    error = data.get("error")

    if not expected_status or not new_status:
        raise HTTPException(status_code=400, detail="expected_status and new_status required")

    if isinstance(expected_status, str):
        expected_list = [expected_status]
    else:
        expected_list = expected_status

    db = get_db()
    runtime_repo = RuntimeRepository(db)
    
    # Use CAS update with expected status list
    if error is not None:
        success = runtime_repo.cas_set_status_with_error(runtime_id, expected_list, new_status, error)
    else:
        success = runtime_repo.cas_set_status(runtime_id, expected_list, new_status)

    if success:
        return {"success": True}

    # fetch current status for idempotency info
    runtime = runtime_repo.get_by_id(runtime_id)
    current_status = runtime.status if runtime else "not_found"
    return {"success": current_status == new_status, "current_status": current_status}


@router.post("/runtimes/{runtime_id}/summarized")
def set_runtime_summarized(runtime_id: str):
    """Set runtime summarized flag to 1 (idempotent)."""
    from gateway.db.repositories import RuntimeRepository

    db = get_db()
    runtime_repo = RuntimeRepository(db)
    
    # Use CAS to set summarized flag
    success = runtime_repo.cas_set_summarized(runtime_id)
    
    if success:
        return {"success": True}

    # Check current value for idempotency info
    runtime = runtime_repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "message": "Runtime not found", "current_value": "not_found"}
    return {
        "success": runtime.summarized == 1,
        "current_value": str(runtime.summarized),
        "message": "Already summarized" if runtime.summarized == 1 else "Update failed",
    }


@router.post("/runtimes/{runtime_id}/hot-cold-summary")
def set_runtime_hot_cold_summary(runtime_id: str, data: Dict[str, Any]):
    """Set both hot and cold summaries for a runtime (v24).
    
    Hot summary: Earlier rounds summarized + last 3 rounds full content
    Cold summary: All rounds summarized by LLM
    """
    from gateway.db.repositories import RuntimeRepository

    hot_summary = data.get("hot_summary", "")
    cold_summary = data.get("cold_summary", "")

    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "error": "Runtime not found"}
    
    runtime_repo.set_hot_cold_summary(runtime_id, hot_summary, cold_summary)

    return {"success": True, "runtime_id": runtime_id}


@router.post("/runtimes/{runtime_id}/need-rest")
def set_runtime_need_rest(runtime_id: str, data: Dict[str, Any]):
    """Set runtime need_rest flag (idempotent).
    
    Note: 使用非 CAS 版本的 set_need_rest，因为：
    1. 这个操作本身是幂等的（设置为固定值）
    2. 不需要检查当前值
    """
    from gateway.db.repositories import RuntimeRepository

    value = bool(data.get("value", True))
    target = 1 if value else 0

    db = get_db()
    runtime_repo = RuntimeRepository(db)
    
    # 直接设置 need_rest 标志（幂等操作）
    runtime_repo.set_need_rest(runtime_id, target)

    # 验证设置是否成功
    runtime = runtime_repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "message": "Runtime not found", "current_value": "not_found"}
    
    return {
        "success": runtime.need_rest == target,
        "current_value": str(runtime.need_rest),
        "message": "OK" if runtime.need_rest == target else "Update failed",
    }


@router.post("/runtimes/{runtime_id}/tool-ports")
def set_runtime_tool_ports(runtime_id: str, data: Dict[str, Any]):
    """Save Tools Server MCP ports for a runtime.
    
    Called by Tools Server when registering/unregistering a runtime.
    Enables recovery after Tools Server restart.
    
    Request body:
        ports: dict - MCP ports (e.g. {"vmuse": 8080}), or null to clear
    """
    from gateway.db.repositories import RuntimeRepository
    
    ports = data.get("ports")
    
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    
    if ports is not None:
        runtime_repo.set_tool_ports(runtime_id, ports)
    else:
        runtime_repo.clear_tool_ports(runtime_id)
    
    return {"success": True, "runtime_id": runtime_id}


@router.delete("/runtimes/{runtime_id}")
def delete_runtime(runtime_id: str):
    """Delete a runtime."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    repo.delete(runtime_id)
    
    return {"status": "ok"}


@router.get("/runtimes/main/{agent_id}")
def get_main_runtime(agent_id: str):
    """Get active main runtime for an agent (v14: from main SubAgent)."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtime = repo.get_active_runtime("main", agent_id)
    
    if not runtime:
        return {"runtime": None}
    
    return {"runtime": _runtime_to_dict(runtime)}


@router.get("/runtimes/subagent/{agent_id}/{subagent_id}")
def get_subagent_runtime(agent_id: str, subagent_id: str):
    """Get active runtime for a SubAgent (v14)."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtime = repo.get_active_runtime(subagent_id, agent_id)
    
    if not runtime:
        return {"runtime": None}
    
    return {"runtime": _runtime_to_dict(runtime)}


@router.get("/runtimes/latest/{agent_id}/{subagent_id}")
def get_latest_runtimes(agent_id: str, subagent_id: str, limit: int = 30):
    """Get latest completed runtimes for a SubAgent (for context preparation, v14)."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    runtimes = repo.get_latest_runtimes(subagent_id, agent_id, limit)
    
    return {"runtimes": [_runtime_to_dict(r) for r in runtimes]}


@router.get("/agents/{agent_id}/subagents/{subagent_id}/has-active-runtime")
def has_active_runtime(agent_id: str, subagent_id: str):
    """Check if SubAgent has an active runtime (status = active)."""
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    has_active = repo.has_active_runtime(subagent_id, agent_id)
    
    return {"has_active_runtime": has_active}



# ==================== Runtime Tools API ====================
# NOTE: /runtimes/list moved to line ~480 (before /runtimes/{runtime_id}) to fix route conflict.

@router.post("/runtimes/{runtime_id}/history")
def get_runtime_history(runtime_id: str, data: Dict[str, Any]):
    """Get message history for a runtime.
    
    Used by Tools Server for runtime_history tool.
    Queries runtime's context which contains the conversation history.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    
    limit = data.get("limit", ServiceConfig.MAX_RUNTIME_CONTEXT_PER_PAGE)
    offset = data.get("offset", 0)
    
    # Get runtime and its context
    runtime = repo.get_by_id(runtime_id)
    if not runtime:
        return {"messages": [], "total": 0, "error": "Runtime not found"}
    
    # Extract messages from context
    context = runtime.context or []
    messages = []
    for msg in context:
        if isinstance(msg, dict) and "role" in msg:
            content = msg.get("content", "")
            if len(content) > ServiceConfig.TEXT_TRUNCATE_MESSAGE:
                content = content[:ServiceConfig.TEXT_TRUNCATE_MESSAGE] + "..."
            messages.append({
                "role": msg.get("role"),
                "content": content,
                "timestamp": msg.get("timestamp"),
            })
    
    # Apply pagination
    total = len(messages)
    messages = messages[offset:offset + limit]
    
    return {
        "messages": messages,
        "total": total,
    }


@router.post("/runtimes/{runtime_id}/send")
def send_to_runtime(runtime_id: str, data: Dict[str, Any]):
    """Send a message to a runtime.
    
    Used by Tools Server for runtime_send tool.
    Appends the message to the runtime's context.
    """
    from gateway.db.repositories import RuntimeRepository
    
    db = get_db()
    repo = RuntimeRepository(db)
    
    message = data.get("message", "")
    
    # Get runtime
    runtime = repo.get_by_id(runtime_id)
    if not runtime:
        return {"success": False, "error": "Runtime not found"}
    
    # Append message to runtime context
    context = runtime.context or []
    context.append({
        "role": "user",
        "content": message,
        "timestamp": utc_now_iso(),
    })
    
    repo.update_context(runtime_id, context)
    
    return {"success": True, "queued": True, "runtime_id": runtime_id}



# ==================== Runtime-First API (v15) ====================
# NOTE: Legacy QEMU API (/vm/qemu/{agent_id}/*) removed in v15.
# Use Runtime-First API: /rt/{runtime_id}/qemu/* instead.
# All APIs accept runtime_id and resolve agent_id/subagent_id from database.
# This simplifies Tools Server tools - they only need to know runtime_id.

# ---------- Memory APIs (via runtime_id) ----------

@router.post("/rt/{runtime_id}/memory/save")
def rt_memory_save(runtime_id: str, data: Dict[str, Any]):
    """Save memory value. Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    return repo.save(
        agent_id=agent_id,
        key=data.get("key"),
        value=data.get("value"),
        namespace=data.get("namespace", "default")
    )


@router.post("/rt/{runtime_id}/memory/recall")
def rt_memory_recall(runtime_id: str, data: Dict[str, Any]):
    """Recall memory value(s). Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    return repo.recall(
        agent_id=agent_id,
        key=data.get("key"),
        namespace=data.get("namespace", "default")
    )


@router.post("/rt/{runtime_id}/memory/delete")
def rt_memory_delete(runtime_id: str, data: Dict[str, Any]):
    """Delete memory value. Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    return repo.delete(
        agent_id=agent_id,
        key=data.get("key"),
        namespace=data.get("namespace", "default")
    )


@router.get("/rt/{runtime_id}/memory/namespaces")
def rt_memory_list_namespaces(runtime_id: str):
    """List all memory namespaces. Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    namespaces = repo.list_namespaces(agent_id)
    return {"success": True, "namespaces": namespaces}


@router.post("/rt/{runtime_id}/memory/task/log")
def rt_memory_log_task(runtime_id: str, data: Dict[str, Any]):
    """Log a task action. Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    return repo.log_task(
        agent_id=agent_id,
        action=data.get("action"),
        details=data.get("details"),
        status=data.get("status", "completed")
    )


@router.post("/rt/{runtime_id}/memory/task/history")
def rt_memory_get_task_history(runtime_id: str, data: Dict[str, Any]):
    """Get task history. Agent ID resolved from runtime."""
    from gateway.db.repositories.memory import MemoryRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MemoryRepository(db)
    return repo.get_task_history(
        agent_id=agent_id,
        limit=data.get("limit", 20),
        status_filter=data.get("status_filter")
    )


# ==================== Notebook 工具 ====================

@router.post("/rt/{runtime_id}/notebook/write")
def rt_notebook_write(runtime_id: str, data: Dict[str, Any]):
    """Write a new notebook entry. Agent ID resolved from runtime."""
    from gateway.db.repositories.notebook import NotebookRepository
    import logging
    
    try:
        _, agent_id, _ = resolve_runtime_ids(runtime_id)
        
        db = get_db()
        repo = NotebookRepository(db)
        return repo.write(
            agent_id=agent_id,
            entry_type=data.get("entry_type") or data.get("type", "observation"),  # 兼容 type 参数
            title=data.get("title", "Untitled"),
            content=data.get("content", ""),
            source=f"runtime:{runtime_id}",
            related_topics=data.get("related_topics") or data.get("tags"),  # 兼容 tags 参数
            relevance_score=data.get("relevance_score", 0.5),
            expires_at=data.get("expires_at"),
        )
    except HTTPException:
        raise
    except Exception as e:
        logging.error(f"[notebook_write] Error for runtime {runtime_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to write notebook entry: {str(e)}")


@router.post("/rt/{runtime_id}/notebook/read")
def rt_notebook_read(runtime_id: str, data: Dict[str, Any]):
    """Read a single notebook entry. Agent ID resolved from runtime."""
    from gateway.db.repositories.notebook import NotebookRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = NotebookRepository(db)
    return repo.read(
        agent_id=agent_id,
        entry_id=data.get("entry_id"),
    )


@router.post("/rt/{runtime_id}/notebook/list")
def rt_notebook_list(runtime_id: str, data: Dict[str, Any]):
    """List notebook entries with filters. Agent ID resolved from runtime."""
    from gateway.db.repositories.notebook import NotebookRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = NotebookRepository(db)
    return repo.list_entries(
        agent_id=agent_id,
        entry_type=data.get("entry_type"),
        status=data.get("status"),
        limit=data.get("limit", 20),
        include_expired=data.get("include_expired", False),
    )


@router.post("/rt/{runtime_id}/notebook/update")
def rt_notebook_update(runtime_id: str, data: Dict[str, Any]):
    """Update a notebook entry. Agent ID resolved from runtime."""
    from gateway.db.repositories.notebook import NotebookRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = NotebookRepository(db)
    return repo.update(
        agent_id=agent_id,
        entry_id=data.get("entry_id"),
        status=data.get("status"),
        content=data.get("content"),
        title=data.get("title"),
        relevance_score=data.get("relevance_score"),
        expires_at=data.get("expires_at"),
    )


@router.post("/rt/{runtime_id}/notebook/delete")
def rt_notebook_delete(runtime_id: str, data: Dict[str, Any]):
    """Delete a notebook entry. Agent ID resolved from runtime."""
    from gateway.db.repositories.notebook import NotebookRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = NotebookRepository(db)
    return repo.delete(
        agent_id=agent_id,
        entry_id=data.get("entry_id"),
    )


# ---------- Chat APIs (via runtime_id) ----------

@router.post("/rt/{runtime_id}/chat/event")
def rt_chat_event(runtime_id: str, data: Dict[str, Any]):
    """Send a chat event. Agent ID resolved from runtime."""
    import uuid
    import asyncio
    from gateway.sse.broadcaster import get_worker_broadcaster
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    event_type = data.get("type", "AGENT_REPLY")
    event_data = data.get("data", {})
    
    # Extract content based on event type
    if event_type == "AGENT_REPLY":
        content = event_data.get("message", "")
        
        # HEARTBEAT_OK 协议：静默完成，不写入消息（双重保险，executor.py 应该已经拦截）
        message_stripped = content.strip() if content else ""
        if message_stripped == "HEARTBEAT_OK" or message_stripped.startswith("HEARTBEAT_OK"):
            print(f"[rt_chat_event] HEARTBEAT_OK received for runtime {runtime_id}, silent completion (fallback)")
            return {"success": True, "silent": True, "message": "Heartbeat acknowledged silently."}
    elif event_type == "AGENT_ASK":
        question = event_data.get("question", "")
        options = event_data.get("options")
        content = question
        if options:
            content += "\n\n选项: " + ", ".join(options)
    elif event_type == "AGENT_NOTIFY":
        content = event_data.get("message", "")
        level = event_data.get("level", "info")
        content = f"[{level}] {content}"
    elif event_type == "AGENT_IMAGE":
        image_url = event_data.get("image_url", "")
        caption = event_data.get("caption", "")
        content = f"[图片: {image_url}]"
        if caption:
            content += f"\n{caption}"
    else:
        content = event_data.get("message", "") or json.dumps(event_data)
    
    # Store message using MessageRepository
    from gateway.db.repositories.message import MessageRepository
    
    db = get_db()
    repo = MessageRepository(db)
    msg = repo.add_message(
        agent_id=agent_id,
        type=event_type,
        content=content,
        status="sent",  # Agent events are already confirmed, skip Monitor queue
    )
    message_id = msg["id"]
    timestamp = msg["timestamp"]
    
    # Broadcast via Worker SSE (for other workers)
    broadcaster = get_worker_broadcaster()
    if broadcaster:
        try:
            from gateway.sse.broadcaster import SSEEvent
            import asyncio
            # Use asyncio.create_task to run async broadcast without blocking
            asyncio.create_task(broadcaster.broadcast(
                event_type=SSEEvent.NEW_MESSAGE,
                data={"message_id": message_id, "agent_id": agent_id, "type": event_type, "content": content},
            ))
        except Exception:
            pass
    
    # Broadcast to UI SSE subscribers (for frontend real-time display)
    # This is the key fix: _chat_subscribers is the SSE channel for frontend UI
    try:
        from main_gateway import _chat_subscribers
        
        # Build message in the format frontend expects
        ui_message = {
            "id": message_id,
            "type": event_type,
            "timestamp": timestamp,
            "agent_id": agent_id,
            # Include both 'message' and 'content' for compatibility
            "message": content,
            "content": content,
        }
        
        # Add extra fields based on event type
        if event_type == "AGENT_ASK":
            ui_message["question"] = event_data.get("question", "")
            ui_message["options"] = event_data.get("options")
            ui_message["request_id"] = event_data.get("request_id")
        elif event_type == "AGENT_NOTIFY":
            ui_message["level"] = event_data.get("level", "info")
        elif event_type == "AGENT_IMAGE":
            ui_message["image_url"] = event_data.get("image_url", "")
            ui_message["caption"] = event_data.get("caption", "")
        
        # Push to all UI SSE subscribers
        for queue in _chat_subscribers.values():
            try:
                queue.put_nowait(ui_message)
            except asyncio.QueueFull:
                pass
        
        print(f"[rt_chat_event] Broadcasted {event_type} to {len(_chat_subscribers)} UI subscribers")
    except Exception as e:
        print(f"[rt_chat_event] Failed to broadcast to UI SSE: {e}")
    
    # Phase 4: Auto-track proactive messages
    # If this is an AGENT_REPLY and the runtime was from a scheduled wake, update last_proactive_at
    if event_type == "AGENT_REPLY":
        try:
            from gateway.db.repositories import RuntimeRepository as _RTRepo
            from gateway.db.repositories.drive import DriveRepository
            _db = get_db()
            _rt_repo = _RTRepo(_db)
            _runtime = _rt_repo.get_by_id(runtime_id)
            if _runtime and getattr(_runtime, 'trigger_type', None) == 'scheduled_wake':
                _drive_repo = DriveRepository(_db)
                _drive_repo.set_last_proactive(_runtime.agent_id)
                print(f"[rt_chat_event] Tracked proactive message for agent {_runtime.agent_id}")
        except Exception as e:
            print(f"[rt_chat_event] Failed to track proactive message: {e}")
    
    return {"success": True, "event_type": event_type, "message_id": message_id}


@router.get("/rt/{runtime_id}/chat/history")
def rt_chat_history(
    runtime_id: str, 
    limit: int = None, 
    summary_length: int = None
):
    """Get chat history. Agent ID resolved from runtime."""
    if limit is None:
        limit = ServiceConfig.DEFAULT_CHAT_LIMIT
    if summary_length is None:
        summary_length = ServiceConfig.DEFAULT_SUMMARY_LENGTH
    from gateway.db.repositories.message import MessageRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MessageRepository(db)
    messages = repo.get_history(agent_id, limit=limit)
    
    result_messages = []
    for m in messages:
        content = m.get("content", "") or ""
        if summary_length > 0 and len(content) > summary_length:
            content = content[:summary_length] + "..."
        msg_type = m.get("type", "")
        role = "user" if msg_type == "USER_MESSAGE" else "assistant"
        result_messages.append({
            "id": m.get("id"), "role": role, "type": msg_type,
            "content": content, "timestamp": m.get("timestamp"),
        })
    
    return {"messages": result_messages, "has_more": len(messages) >= limit}


@router.get("/rt/{runtime_id}/chat/message/{message_id}")
def rt_chat_get_message(runtime_id: str, message_id: str):
    """Get full content of a chat message."""
    from gateway.db.repositories.message import MessageRepository
    
    # Validate runtime exists (also verifies access)
    resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = MessageRepository(db)
    message = repo.get_message(message_id)
    if not message:
        return {"success": False, "error": "Message not found"}
    
    msg_type = message.get("type", "")
    role = "user" if msg_type == "USER_MESSAGE" else "assistant"
    return {
        "success": True, "id": message.get("id"), "role": role,
        "type": msg_type, "content": message.get("content"), "timestamp": message.get("timestamp"),
    }


# ---------- SubAgent APIs (via runtime_id) ----------

@router.post("/rt/{runtime_id}/subagent/spawn")
def rt_subagent_spawn(runtime_id: str, data: Dict[str, Any]):
    """Spawn a SubAgent. Agent ID and parent SubAgent ID resolved from runtime."""
    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    import uuid
    
    _, agent_id, parent_subagent_id = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    task_description = data.get("task", "")
    share_context = data.get("share_context", False)
    timeout_minutes = data.get("timeout_minutes", 30)
    
    now = utc_now()
    timeout_at = (now + timedelta(minutes=timeout_minutes)).isoformat()
    
    # Create sub SubAgent
    subagent = subagent_repo.create_sub_subagent(
        agent_id, parent_subagent_id, task=task_description, timeout_at=timeout_at,
    )
    
    # Prepare initial context
    initial_context = []
    if share_context:
        parent_runtime = runtime_repo.get_by_id(runtime_id)
        if parent_runtime and parent_runtime.context:
            initial_context = parent_runtime.context.copy()
    
    initial_context.append({"role": "user", "content": f"[SubAgent Task]\n{task_description}"})
    
    # v3: 不再设置 awaking 状态，由 message_process Saga 通过 get_or_create_runtime 原子操作处理
    # SubAgent 创建时默认是 sleeping 状态，Watchdog 会监测消息并触发 Saga
    
    # v2.1: 写入 SPAWN_SUBAGENT 消息，由 Watchdog 创建 Saga
    # Gateway 不再直接调用 Queue Service
    from gateway.db.repositories.message import MessageRepository
    import uuid
    
    trigger_id = f"spawn-{subagent.subagent_id}-{uuid.uuid4().hex[:8]}"
    message_repo = MessageRepository(db)
    
    # 写入消息，Watchdog 会监测并创建 runtime_start saga
    msg = message_repo.add_message(
        agent_id=agent_id,
        type="SPAWN_SUBAGENT",
        content=task_description,
        status="sending",  # Watchdog 监测 sending 状态
        metadata={
            "subagent_id": subagent.subagent_id,
            "trigger_id": trigger_id,
            "initial_context": initial_context,
            "parent_subagent_id": parent_subagent_id,
        }
    )
    
    print(f"[Gateway] Created SPAWN_SUBAGENT message {msg['id']} for subagent {subagent.subagent_id}")
    
    return {
        "subagent_id": subagent.subagent_id,
        "message_id": msg["id"],
    }


@router.get("/rt/{runtime_id}/subagent/{target_subagent_id}/status")
def rt_subagent_query(runtime_id: str, target_subagent_id: str):
    """Query SubAgent status. Agent ID resolved from runtime."""
    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    subagent = subagent_repo.get_by_id(target_subagent_id, agent_id)
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")
    
    # Check timeout
    if subagent.status == SubagentStatus.RUNNING.value and subagent.timeout_at:
        try:
            timeout_at = datetime.fromisoformat(subagent.timeout_at)
            if utc_now() > timeout_at:
                subagent_repo.set_failed(target_subagent_id, agent_id, error="SubAgent timed out")
                subagent = subagent_repo.get_by_id(target_subagent_id, agent_id)
        except (ValueError, TypeError):
            pass
    
    completed = subagent.status in (
        SubagentStatus.COMPLETED.value,
        SubagentStatus.FAILED.value,
        SubagentStatus.CANCELLED.value,
        SubagentStatus.SLEEPING.value
    )
    response = {
        "subagent_id": target_subagent_id, "status": subagent.status, "completed": completed,
        "progress": getattr(subagent, "progress", None),
        "result": getattr(subagent, "result", None),
        "error": getattr(subagent, "error", None),
    }
    
    runtimes = runtime_repo.get_latest_runtimes(target_subagent_id, agent_id, limit=1)
    if runtimes:
        rt = runtimes[0]
        response["runtime_id"] = rt.runtime_id
        response["runtime_status"] = rt.status
        if not response["result"] and rt.status == RuntimeStatus.COMPLETED.value and rt.context:
            for msg in reversed(rt.context):
                if msg.get("role") == "assistant":
                    response["result"] = msg.get("content", "")
                    break
    
    return response


@router.post("/rt/{runtime_id}/subagent/{target_subagent_id}/cancel")
def rt_subagent_cancel(runtime_id: str, target_subagent_id: str):
    """Cancel a running SubAgent."""
    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    subagent = subagent_repo.get_by_id(target_subagent_id, agent_id)
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")
    
    if subagent.status != SubagentStatus.RUNNING.value:
        return {"success": False, "reason": f"SubAgent is not running (status: {subagent.status})"}
    
    subagent_repo.set_cancelled(target_subagent_id, agent_id)
    
    # Cancel active runtimes
    runtime_ids = runtime_repo.get_runtime_ids_for_subagent(target_subagent_id, agent_id)
    for rid in runtime_ids:
        runtime_repo.set_status(rid, 'cancelled')
    
    return {"success": True}


# ---------- QEMU APIs (via runtime_id) ----------

@router.post("/rt/{runtime_id}/qemu/ssh-exec")
async def rt_qemu_ssh_exec(runtime_id: str, data: Dict[str, Any]):
    """Execute command via SSH on VM. Agent ID resolved from runtime."""
    import asyncio
    from gateway.vm.ssh import get_ssh_key_manager
    from gateway.config.agents import allocate_ports_for_agent, get_agent_config_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    command = data.get("command", "")
    timeout = data.get("timeout", 30)
    
    # Get agent port configuration from database
    config_mgr = get_agent_config_manager()
    agent = config_mgr.get_agent(agent_id)
    
    if not agent or not agent.vm or not agent.vm.ports:
        raise HTTPException(status_code=404, detail="Agent not found or has no port configuration")
    
    ssh_port = agent.vm.ports.ssh
    
    try:
        import asyncssh
        ssh_manager = get_ssh_key_manager()
        key_path = ssh_manager.get_private_key_path()
        
        async with asyncssh.connect(
            host="127.0.0.1", port=ssh_port, username="ubuntu",
            known_hosts=None, client_keys=[str(key_path)], compression_algs=None,
        ) as conn:
            result = await asyncio.wait_for(conn.run(command, check=False), timeout=timeout)
            # 注意：success=True 表示 SSH 连接成功且命令执行完成
            # exit_code 是命令本身的退出码，由 LLM 根据上下文判断是否符合预期
            return {
                "stdout": result.stdout, "stderr": result.stderr,
                "exit_code": result.exit_status, "success": True
            }
    except asyncio.TimeoutError:
        return {"error": f"Command timed out after {timeout}s", "success": False}
    except Exception as e:
        return {"error": str(e), "success": False}


@router.get("/rt/{runtime_id}/qemu/status")
def rt_qemu_status(runtime_id: str):
    """Get QEMU VM status. Agent ID resolved from runtime."""
    import os
    from gateway.config.agents import get_agent_config_manager
    from gateway.vm.repository import VmProcessRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    config_mgr = get_agent_config_manager()
    agent = config_mgr.get_agent(agent_id)
    
    if not agent or not agent.vm or not agent.vm.ports:
        raise HTTPException(status_code=404, detail="Agent not found or has no port configuration")
    
    ports = agent.vm.ports
    
    # Get VM process info from database (not from filesystem PID file)
    repo = VmProcessRepository()
    process_info = repo.get_process(agent_id)
    
    qemu_running = False
    qemu_pid = None
    
    if process_info:
        qemu_pid = process_info.get("pid")
        # Check if process is actually alive
        if qemu_pid:
            try:
                os.kill(qemu_pid, 0)
                qemu_running = True
            except (ProcessLookupError, PermissionError):
                # Process not found or no permission - mark as not running
                qemu_running = False
    
    return {
        "success": True,
        "qemu_running": qemu_running,
        "qemu_pid": qemu_pid,
        "ports": {"ssh": ports.ssh},
        "agent_id": agent_id,
    }


@router.post("/rt/{runtime_id}/qemu/start")
def rt_qemu_start(runtime_id: str, data: Dict[str, Any]):
    """Start the QEMU VM. Agent ID resolved from runtime."""
    from gateway.vm import get_vm_manager
    from gateway.config.agents import get_agent_config_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    memory = data.get("memory", "4096")
    cpus = data.get("cpus", 4)
    
    try:
        manager = get_vm_manager()
        result = manager.start(
            agent_id=agent_id,
            memory=memory,
            cpus=cpus,
        )
        return {"success": True, **result}
    except Exception as e:
        return {"success": False, "error": str(e)}


@router.post("/rt/{runtime_id}/qemu/shutdown")
def rt_qemu_shutdown(runtime_id: str, data: Dict[str, Any]):
    """Shutdown the QEMU VM gracefully. Agent ID resolved from runtime."""
    from gateway.vm import get_vm_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    graceful = data.get("graceful", True)
    quick = data.get("quick", False)
    
    try:
        manager = get_vm_manager()
        result = manager.stop(
            agent_id=agent_id,
            graceful=graceful,
            quick=quick,
        )
        return {"success": True, **result}
    except Exception as e:
        return {"success": False, "error": str(e)}


@router.post("/rt/{runtime_id}/qemu/restart")
def rt_qemu_restart(runtime_id: str, data: Dict[str, Any]):
    """Restart the QEMU VM (stop then start). Agent ID resolved from runtime."""
    from gateway.vm import get_vm_manager
    from gateway.config.agents import get_agent_config_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    graceful = data.get("graceful", True)
    
    try:
        manager = get_vm_manager()
        
        # Stop the VM first
        stop_result = manager.stop(
            agent_id=agent_id,
            graceful=graceful,
            quick=False,  # Use normal timeout for restart
        )
        
        # Start the VM again
        start_result = manager.start(
            agent_id=agent_id,
            memory="4096",  # Default memory
            cpus=4,         # Default CPUs
        )
        
        return {
            "success": True,
            "stop_result": stop_result,
            "start_result": start_result,
        }
    except Exception as e:
        return {"success": False, "error": str(e)}

# ---------- Task APIs (via runtime_id) ----------

@router.post("/rt/{runtime_id}/tasks/spawn")
def rt_task_spawn(runtime_id: str, data: Dict[str, Any]):
    """Spawn a new task. Agent ID resolved from runtime."""
    from gateway.core.task_manager import get_task_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.spawn(
        task_type=data.get("task_type", "tool"),
        config=data.get("config", {}),
        label=data.get("label"),
        timeout_seconds=data.get("timeout_seconds", 0),
        notify_on=data.get("notify_on"),
        parent_session_key=runtime_id,  # Use runtime_id as session key
        agent_id=agent_id,
    )


@router.get("/rt/{runtime_id}/tasks")
def rt_task_list(runtime_id: str, status: Optional[str] = None):
    """List tasks. Agent ID resolved from runtime."""
    from gateway.core.task_manager import get_task_manager
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    status_filter = [status] if status else None
    return task_manager.get_status(task_id=None, status_filter=status_filter, agent_id=agent_id)


# Note: task_query, task_cancel, task_summary don't need runtime_id - they use task_id directly


# ==================== Drive 工具 (Agent 自驱力) ====================

@router.get("/internal/rt/{runtime_id}/drive")
def get_runtime_drive(runtime_id: str):
    """
    Get drive configuration for a runtime's agent.
    Used by Tools Server to fetch bootstrap files for memory_update tool.
    """
    from gateway.db.repositories.drive import DriveRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = DriveRepository(db)
    
    drive = repo.get(agent_id)
    if not drive:
        # 返回默认值
        return {
            "agent_id": agent_id,
            "soul_md": "",
            "heartbeat_md": "",
            "memory_md": "",
            "user_md": "",
            "active_hours_start": "09:00",
            "active_hours_end": "22:00",
            "active_hours_timezone": "Asia/Shanghai",
        }
    
    return {
        "agent_id": agent_id,
        "soul_md": drive.get("soul_md", ""),
        "heartbeat_md": drive.get("heartbeat_md", ""),
        "memory_md": drive.get("memory_md", ""),
        "user_md": drive.get("user_md", ""),
        "active_hours_start": drive.get("active_hours_start", "09:00"),
        "active_hours_end": drive.get("active_hours_end", "22:00"),
        "active_hours_timezone": drive.get("active_hours_timezone", "Asia/Shanghai"),
    }


@router.post("/rt/{runtime_id}/drive/get")
def rt_drive_get(runtime_id: str):
    """Get agent drive configuration. Agent ID resolved from runtime."""
    from gateway.db.repositories.drive import DriveRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = DriveRepository(db)
    return repo.get_or_create(agent_id)


@router.post("/rt/{runtime_id}/drive/update-profile")
def rt_drive_update_profile(runtime_id: str, data: Dict[str, Any]):
    """Update a key in user_profile. Agent ID resolved from runtime."""
    from gateway.db.repositories.drive import DriveRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = DriveRepository(db)
    return repo.update_profile(
        agent_id=agent_id,
        key=data.get("key"),
        value=data.get("value"),
        reason=data.get("reason"),
    )


@router.post("/rt/{runtime_id}/drive/update")
def rt_drive_update(runtime_id: str, data: Dict[str, Any]):
    """Update drive fields (relationship, proactiveness, etc). Agent ID resolved from runtime."""
    from gateway.db.repositories.drive import DriveRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = DriveRepository(db)
    return repo.update_drive(
        agent_id=agent_id,
        relationship_delta=data.get("relationship_delta"),
        proactiveness_delta=data.get("proactiveness_delta"),
        reason=data.get("reason"),
    )
