"""
Internal API module: subagent

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import (
    resolve_runtime_ids,
    get_runtime_context,
    _runtime_to_dict,
    _subagent_to_dict,
    maybe_forward_to_runtime_orchestrator,
)

router = APIRouter(tags=["internal"])

# ==================== SubAgent Operations (v14) ====================

@router.get("/subagents/due-wake")
async def get_subagents_due_for_wake():
    """Get sleeping SubAgents whose wake_at timer has expired.
    
    Used by SchedulerWorker to find agents that need to be woken up.
    
    Returns:
        {"subagents": [{"agent_id": ..., "subagent_id": ..., "wake_at": ..., "handoff_notes": ...}, ...]}
    """
    proxied = await maybe_forward_to_runtime_orchestrator("GET", "/internal/subagents/due-wake")
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)

    due = repo.get_due_for_wake()

    return {
        "subagents": [
            {
                "agent_id": sa.agent_id,
                "subagent_id": sa.subagent_id,
                "wake_at": sa.wake_at,
                "wake_triggers": sa.wake_triggers,
                "handoff_notes": sa.handoff_notes,
            }
            for sa in due
        ]
    }


@router.get("/subagents/{agent_id}/main")
async def get_main_subagent(agent_id: str):
    """Get the main SubAgent for an agent (creates if not exists)."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/subagents/{agent_id}/main"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    subagent = repo.get_or_create_main_subagent(agent_id)

    return _subagent_to_dict(subagent)


@router.get("/subagents/{agent_id}/{subagent_id}")
async def get_subagent(agent_id: str, subagent_id: str):
    """Get a SubAgent by ID."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/subagents/{agent_id}/{subagent_id}"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    subagent = repo.get_by_id(subagent_id, agent_id)

    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")

    return _subagent_to_dict(subagent)


# DELETED: wake_subagent() - 用 get_or_create_runtime 替代


@router.post("/subagents/{agent_id}/{subagent_id}/sleeping")
async def set_subagent_sleeping(agent_id: str, subagent_id: str):
    """Set SubAgent to sleeping status."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/sleeping", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    repo.set_sleeping(subagent_id, agent_id)
    subagent = repo.get_by_id(subagent_id, agent_id)
    return {
        "success": True,
        "status": subagent.status if subagent else "sleeping",
        "previous_status": None,
    }


@router.post("/subagents/{agent_id}/{subagent_id}/awake")
async def set_subagent_awake(agent_id: str, subagent_id: str):
    """Set SubAgent to awake status (after runtime created successfully)."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/awake", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    repo.set_awake(subagent_id, agent_id)
    subagent = repo.get_by_id(subagent_id, agent_id)
    return {
        "success": True,
        "status": subagent.status if subagent else "awake",
        "previous_status": None,
    }


@router.post("/subagents/{agent_id}/{subagent_id}/summarizing")
async def set_subagent_summarizing(agent_id: str, subagent_id: str):
    """Set SubAgent to summarizing status."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/summarizing", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    repo.set_summarizing(subagent_id, agent_id)

    return {"status": "ok"}


@router.post("/subagents/{agent_id}/{subagent_id}/completed")
async def set_subagent_completed(agent_id: str, subagent_id: str, data: Dict[str, Any] = None):
    """Set SubAgent to completed status with result.

    If the SubAgent already has a result (e.g., from subagent_report tool),
    the existing result will be preserved and the new result will be ignored.
    This allows SubAgents to proactively report their results before completion.
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/completed",
        json_body=data,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)

    # Check if SubAgent already has a result (from subagent_report tool)
    existing_subagent = repo.get_by_id(subagent_id, agent_id)
    existing_result = existing_subagent.result if existing_subagent else None

    # If already has result, preserve it; otherwise use the new result
    result = data.get("result") if data else None
    if existing_result:
        # Keep the existing result (from subagent_report)
        result = existing_result

    repo.set_completed(subagent_id, agent_id, result=result)

    return {"status": "ok", "result_preserved": bool(existing_result)}


@router.post("/subagents/{agent_id}/{subagent_id}/failed")
async def set_subagent_failed(agent_id: str, subagent_id: str, data: Dict[str, Any] = None):
    """Set SubAgent to failed status with error message."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/failed",
        json_body=data,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)

    error = data.get("error") if data else None
    repo.set_failed(subagent_id, agent_id, error=error)

    return {"status": "ok"}


@router.patch("/subagents/{agent_id}/{subagent_id}")
async def update_subagent(agent_id: str, subagent_id: str, data: Dict[str, Any]):
    """Update SubAgent fields."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "PATCH", f"/internal/subagents/{agent_id}/{subagent_id}", json_body=data
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    
    if "historical_summary" in data:
        repo.update_historical_summary(subagent_id, agent_id, data["historical_summary"])
    
    if "wake_triggers" in data or "handoff_notes" in data:
        repo.update_wake_triggers(
            subagent_id, 
            agent_id,
            data.get("wake_triggers", [{"type": "user_response"}]),
            data.get("handoff_notes")
        )
    
    return {"status": "ok"}


@router.post("/subagents/{agent_id}/spawn")
async def spawn_subagent(agent_id: str, data: Dict[str, Any]):
    """
    Spawn a new SubAgent and its Runtime (async mode).
    
    Creates a sub SubAgent and triggers RuntimeStart Saga.
    Returns the subagent_id immediately. Use /status to poll for completion.
    
    Args (JSON body):
        task: Task description for the SubAgent
        share_context: If True, copy context from parent runtime
        parent_subagent_id: Parent SubAgent (defaults to main)
        timeout_minutes: Timeout in minutes (default 30)
    
    Returns:
        subagent_id: Use this to query status
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/spawn", json_body=data
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    from datetime import datetime, timedelta
    import uuid
    
    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    # Get parent subagent_id (defaults to main)
    parent_subagent_id = data.get("parent_subagent_id")
    if not parent_subagent_id:
        main_subagent = subagent_repo.get_or_create_main_subagent(agent_id)
        parent_subagent_id = main_subagent.subagent_id
    
    # Parse parameters
    task_description = data.get("task", "")
    share_context = data.get("share_context", False)
    timeout_minutes = data.get("timeout_minutes", 30)
    
    # Calculate timeout
    now = datetime.utcnow()
    timeout_at = (now + timedelta(minutes=timeout_minutes)).isoformat()
    
    # Create sub SubAgent with async fields
    subagent = subagent_repo.create_sub_subagent(
        agent_id, 
        parent_subagent_id,
        task=task_description,
        timeout_at=timeout_at,
    )
    
    # Prepare initial context
    initial_context = []
    
    # If sharing context, copy from parent's active runtime
    if share_context:
        parent_runtime = runtime_repo.get_active_runtime(parent_subagent_id, agent_id)
        if parent_runtime and parent_runtime.context:
            # Copy context but mark it as inherited
            initial_context = parent_runtime.context.copy()
    
    # Add task as user message
    initial_context.append({
        "role": "user",
        "content": f"[SubAgent Task]\n{task_description}"
    })
    
    # v3: 不再设置 awaking 状态，由 message_process Saga 通过 get_or_create_runtime 原子操作处理
    # SubAgent 创建时默认是 sleeping 状态，Watchdog 会监测消息并触发 Saga
    
    # v2.1: 写入 SPAWN_SUBAGENT 消息，由 Watchdog 创建 Saga
    # Gateway 不再直接调用 Queue Service
    from gateway.db.repositories.message import MessageRepository
    
    trigger_id = f"spawn-{subagent.subagent_id}-{uuid.uuid4().hex[:8]}"
    message_repo = MessageRepository(db)
    
    # 写入消息，Watchdog 会监测并创建 runtime_start saga
    msg = message_repo.add_message(
        agent_id=agent_id,
        type="SPAWN_SUBAGENT",
        content=task_description,
        status="sending",  # Watchdog 监测 sending 状态
        metadata={
            "subagent_id": subagent.subagent_id,
            "trigger_id": trigger_id,
            "initial_context": initial_context,
            "parent_subagent_id": parent_subagent_id,
        }
    )
    
    print(f"[Gateway] Created SPAWN_SUBAGENT message {msg['id']} for subagent {subagent.subagent_id}")
    
    return {
        "subagent_id": subagent.subagent_id,
        "message_id": msg["id"],
    }


@router.get("/subagents/{agent_id}/{subagent_id}/status")
async def get_subagent_status(agent_id: str, subagent_id: str):
    """
    Get SubAgent status for async spawn polling.
    
    Returns:
        subagent_id: SubAgent ID
        status: running | completed | failed | cancelled | sleeping
        completed: True if finished (completed/failed/cancelled)
        progress: Current progress description
        result: Final result (when completed)
        error: Error message (when failed)
        runtime_id: Active runtime ID
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/subagents/{agent_id}/{subagent_id}/status"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    from datetime import datetime
    
    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    subagent = subagent_repo.get_by_id(subagent_id, agent_id)
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")
    
    # Check timeout
    if subagent.status == SubagentStatus.RUNNING.value and subagent.timeout_at:
        try:
            timeout_at = datetime.fromisoformat(subagent.timeout_at)
            if datetime.utcnow() > timeout_at:
                # Mark as failed due to timeout
                subagent_repo.set_failed(
                    subagent_id, agent_id, 
                    error="SubAgent timed out"
                )
                subagent = subagent_repo.get_by_id(subagent_id, agent_id)
        except (ValueError, TypeError):
            pass  # Invalid timeout format, skip check
    
    # Determine completion status
    completed = subagent.status in (
        SubagentStatus.COMPLETED.value,
        SubagentStatus.FAILED.value,
        SubagentStatus.CANCELLED.value,
        SubagentStatus.SLEEPING.value
    )
    
    response = {
        "subagent_id": subagent_id,
        "status": subagent.status,
        "completed": completed,
        "progress": getattr(subagent, "progress", None),
        "result": getattr(subagent, "result", None),
        "error": getattr(subagent, "error", None),
    }
    
    # Get the latest runtime
    runtimes = runtime_repo.get_latest_runtimes(subagent_id, agent_id, limit=1)
    if runtimes:
        runtime = runtimes[0]
        response["runtime_id"] = runtime.runtime_id
        response["runtime_status"] = runtime.status
        
        # If no explicit result set, try to get from runtime context
        if not response["result"] and runtime.status == RuntimeStatus.COMPLETED.value and runtime.context:
            for msg in reversed(runtime.context):
                if msg.get("role") == "assistant":
                    response["result"] = msg.get("content", "")
                    break
    
    return response


@router.post("/subagents/{agent_id}/{subagent_id}/cancel")
async def cancel_subagent(agent_id: str, subagent_id: str):
    """
    Cancel a running SubAgent.

    Sets status to 'cancelled' and cancels all pending tasks.
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/cancel", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository, RuntimeRepository
    from datetime import datetime

    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)

    subagent = subagent_repo.get_by_id(subagent_id, agent_id)
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")

    # Only cancel if running
    if subagent.status != SubagentStatus.RUNNING.value:
        return {"success": False, "reason": f"SubAgent is not running (status: {subagent.status})"}

    # Set SubAgent to cancelled
    subagent_repo.set_cancelled(subagent_id, agent_id)

    # Cancel all active runtimes for this SubAgent
    runtime_ids = runtime_repo.get_runtime_ids_for_subagent(subagent_id, agent_id)
    for runtime_id in runtime_ids:
        runtime_repo.set_status(runtime_id, 'cancelled')

    return {"success": True}


@router.delete("/subagents/{agent_id}/{subagent_id}")
async def delete_subagent(agent_id: str, subagent_id: str):
    """Delete a SubAgent and its runtimes."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "DELETE", f"/internal/subagents/{agent_id}/{subagent_id}", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository, RuntimeRepository

    db = get_db()
    subagent_repo = SubAgentRepository(db)
    runtime_repo = RuntimeRepository(db)
    
    # Delete runtimes for this subagent
    with db.transaction("agent", resource_id=agent_id, timeout=ServiceConfig.DB_TRANSACTION_TIMEOUT):
        db.execute(
            "DELETE FROM agent_runtimes WHERE subagent_id = ? AND agent_id = ?",
            (subagent_id, agent_id)
        )
    
    # Delete subagent
    subagent_repo.delete(subagent_id, agent_id)
    
    return {"status": "ok"}



# ==================== HRL and Summary Lock Operations (v24) ====================

@router.get("/subagents/{agent_id}/{subagent_id}/hrl")
async def get_hrl(agent_id: str, subagent_id: str):
    """Get Hot Runtime List for a SubAgent.

    Returns:
        hrl: List of runtime_ids in HRL
        length: Number of runtimes in HRL
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/subagents/{agent_id}/{subagent_id}/hrl"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    hrl = repo.get_hrl(subagent_id, agent_id)

    return {
        "hrl": hrl,
        "length": len(hrl),
    }


@router.post("/subagents/{agent_id}/{subagent_id}/hrl/add")
async def add_to_hrl(agent_id: str, subagent_id: str, data: Dict[str, Any]):
    """Add a runtime to HRL.
    
    Body:
        runtime_id: Runtime ID to add
        
    Returns:
        success: True if added, False if already exists
        hrl: Updated HRL list
        length: Updated HRL length
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/hrl/add",
        json_body=data,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)

    runtime_id = data.get("runtime_id")
    if not runtime_id:
        raise HTTPException(status_code=400, detail="runtime_id is required")

    success = repo.add_to_hrl(subagent_id, agent_id, runtime_id)
    hrl = repo.get_hrl(subagent_id, agent_id)

    return {
        "success": success,
        "hrl": hrl,
        "length": len(hrl),
    }


@router.get("/subagents/{agent_id}/{subagent_id}/summary-lock")
async def get_summary_lock(agent_id: str, subagent_id: str):
    """Get summary_lock status for a SubAgent.

    Returns:
        summary_lock: 0 = idle, 1 = locked
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/subagents/{agent_id}/{subagent_id}/summary-lock"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    lock = repo.get_summary_lock(subagent_id, agent_id)

    return {"summary_lock": lock}


@router.post("/subagents/{agent_id}/{subagent_id}/summary-lock/acquire")
async def acquire_summary_lock(agent_id: str, subagent_id: str):
    """Try to acquire summary_lock using CAS.
    
    Returns:
        success: True if lock acquired, False if lock already held
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/summary-lock/acquire",
        json_body=None,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    success = repo.acquire_summary_lock(subagent_id, agent_id)

    return {"success": success}


@router.post("/subagents/{agent_id}/{subagent_id}/summary-lock/release")
async def release_summary_lock(agent_id: str, subagent_id: str):
    """Release summary_lock.
    
    Returns:
        success: Always True
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/summary-lock/release",
        json_body=None,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)
    repo.release_summary_lock(subagent_id, agent_id)

    return {"success": True}


@router.post("/subagents/{agent_id}/{subagent_id}/merge-history")
async def merge_history(agent_id: str, subagent_id: str, data: Dict[str, Any]):
    """Atomically update historical_summary and remove runtimes from HRL.
    
    Body:
        new_history: New merged historical summary
        remove_runtime_ids: List of runtime_ids to remove from HRL
        
    Returns:
        success: True if successful
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/subagents/{agent_id}/{subagent_id}/merge-history",
        json_body=data,
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories import SubAgentRepository

    db = get_db()
    repo = SubAgentRepository(db)

    new_history = data.get("new_history", "")
    remove_runtime_ids = data.get("remove_runtime_ids", [])

    success = repo.atomic_update_history_and_hrl(
        subagent_id=subagent_id,
        agent_id=agent_id,
        new_history=new_history,
        remove_runtime_ids=remove_runtime_ids
    )

    return {"success": success}


# ==================== Drive Prompt Data (Phase 3) ====================

@router.get("/agents/{agent_id}/drive")
async def get_agent_drive(agent_id: str):
    """Get agent drive record for Drive Prompt builder."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/agents/{agent_id}/drive"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories.drive import DriveRepository

    db = get_db()
    repo = DriveRepository(db)
    return repo.get_or_create(agent_id)


@router.get("/agents/{agent_id}/notebook-summary")
async def get_agent_notebook_summary(agent_id: str):
    """Get notebook summary for Drive Prompt builder."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/agents/{agent_id}/notebook-summary"
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories.notebook import NotebookRepository

    db = get_db()
    repo = NotebookRepository(db)
    return repo.get_summary(agent_id)


# ==================== Agent Info & Drive Lifecycle (Phase 4) ====================

@router.post("/agents/{agent_id}/drive/increment-interaction")
async def increment_drive_interaction(agent_id: str):
    """Increment interaction count and reset no-response streak in agent_drive.
    
    Called by Watchdog when processing USER_MESSAGE.
    """
    proxied = await maybe_forward_to_runtime_orchestrator(
        "POST", f"/internal/agents/{agent_id}/drive/increment-interaction", json_body=None
    )
    if proxied is not None:
        return proxied

    from gateway.db.repositories.drive import DriveRepository

    db = get_db()
    repo = DriveRepository(db)
    return repo.increment_interaction(agent_id)


@router.get("/agents/{agent_id}/info")
async def get_agent_info(agent_id: str):
    """Get basic agent info for system prompt builder."""
    proxied = await maybe_forward_to_runtime_orchestrator(
        "GET", f"/internal/agents/{agent_id}/info"
    )
    if proxied is not None:
        return proxied

    from gateway.config.agents import get_agent_config_manager

    config_mgr = get_agent_config_manager()
    agent = config_mgr.get_agent(agent_id)

    if not agent:
        return {"name": "NovAIC Agent", "os": "unknown", "agent_id": agent_id}

    return {
        "name": agent.name,
        "os": getattr(agent, "os", "unknown"),
        "agent_id": agent_id,
    }
