"""
Internal API module: task

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== TaskManager API (for Tools Server) ====================

@router.post("/tasks/spawn")
def task_spawn(data: Dict[str, Any]):
    """Spawn a new task.
    
    Used by Tools Server to create background tasks.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    result = task_manager.spawn(
        task_type=data.get("task_type", "tool"),
        config=data.get("config", {}),
        label=data.get("label"),
        timeout_seconds=data.get("timeout_seconds", 0),
        notify_on=data.get("notify_on"),
        parent_session_key=data.get("parent_session_key"),
        agent_id=data.get("agent_id"),
    )
    return result


@router.post("/tasks/create-completed")
def task_create_completed(data: Dict[str, Any]):
    """Create an immediately completed task for truncated output storage.
    
    Used by Tools Server for _auto_truncate_result.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    task_id = task_manager.create_completed(
        tool_name=data.get("tool_name", "unknown"),
        truncated_result=data.get("truncated_result", ""),
        full_output=data.get("full_output", ""),
        ttl_hours=data.get("ttl_hours", 24),
        agent_id=data.get("agent_id"),
    )
    return {"task_id": task_id}


@router.get("/tasks/{task_id}")
def task_get_status(
    task_id: str,
    include_outputs: bool = False,
    start_line: Optional[int] = None,
    end_line: Optional[int] = None,
    tail_lines: Optional[int] = None,
):
    """Get task status by ID.
    
    Used by Tools Server for task_query tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.get_status(
        task_id=task_id,
        include_outputs=include_outputs,
        start_line=start_line,
        end_line=end_line,
        tail_lines=tail_lines,
    )


@router.get("/tasks")
def task_list(
    status: Optional[str] = None,
    agent_id: Optional[str] = None,
):
    """List tasks.
    
    Used by Tools Server for task_list tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    status_filter = [status] if status else None
    return task_manager.get_status(
        task_id=None,
        status_filter=status_filter,
        agent_id=agent_id,
    )


@router.post("/tasks/{task_id}/cancel")
def task_cancel(task_id: str, reason: Optional[str] = None):
    """Cancel a task.
    
    Used by Tools Server for task_cancel tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.cancel(task_id, reason)


@router.get("/tasks/{task_id}/result")
def task_get_result(task_id: str, format: str = "summary"):
    """Get task result.
    
    Used by Tools Server for task_result tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.get_result(task_id, format=format)


# ==================== Four-Quadrant Task API (四象限任务系统) ====================
# Internal API for tools_server to manage quadrant tasks


class QuadrantTaskCreateRequest(BaseModel):
    title: str
    quadrant: str  # q1/q2/q3/q4
    source: str
    description: Optional[str] = ""
    reasoning: Optional[str] = None
    due_date: Optional[str] = None
    context: Optional[str] = None
    related_profile_keys: Optional[List[str]] = None


class QuadrantTaskUpdateRequest(BaseModel):
    status: Optional[str] = None
    quadrant: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    due_date: Optional[str] = None


class QuadrantTaskCompleteRequest(BaseModel):
    notes: Optional[str] = None


class GrowthLogRequest(BaseModel):
    content: str
    category: Optional[str] = "learning"


@router.post("/rt/{runtime_id}/quadrant-tasks")
def create_quadrant_task(runtime_id: str, request: QuadrantTaskCreateRequest):
    """创建四象限任务
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.create(
        agent_id=agent_id,
        title=request.title,
        quadrant=request.quadrant,
        source=request.source,
        description=request.description or "",
        reasoning=request.reasoning,
        due_date=request.due_date,
        context=request.context,
        related_profile_keys=request.related_profile_keys,
    )


@router.get("/rt/{runtime_id}/quadrant-tasks")
def list_quadrant_tasks(
    runtime_id: str,
    quadrant: Optional[str] = None,
    status: Optional[str] = "pending",
    limit: int = 20,
):
    """列出四象限任务
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.list_by_quadrant(
        agent_id=agent_id,
        quadrant=quadrant,
        status=status,
        limit=limit,
    )


@router.get("/rt/{runtime_id}/quadrant-tasks/board")
def get_quadrant_board(runtime_id: str):
    """获取四象限任务看板摘要
    
    供 tools_server 调用的内部 API。
    返回按象限分组的活跃任务。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.get_board_summary(agent_id=agent_id)


@router.get("/rt/{runtime_id}/quadrant-tasks/{task_id}")
def get_quadrant_task(runtime_id: str, task_id: int):
    """获取单个四象限任务详情
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.get(agent_id=agent_id, task_id=task_id)


@router.patch("/rt/{runtime_id}/quadrant-tasks/{task_id}")
def update_quadrant_task(runtime_id: str, task_id: int, request: QuadrantTaskUpdateRequest):
    """更新四象限任务
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.update(
        agent_id=agent_id,
        task_id=task_id,
        status=request.status,
        quadrant=request.quadrant,
        title=request.title,
        description=request.description,
        due_date=request.due_date,
    )


@router.post("/rt/{runtime_id}/quadrant-tasks/{task_id}/complete")
def complete_quadrant_task(runtime_id: str, task_id: int, request: QuadrantTaskCompleteRequest):
    """完成四象限任务
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.complete(
        agent_id=agent_id,
        task_id=task_id,
        notes=request.notes,
    )


@router.delete("/rt/{runtime_id}/quadrant-tasks/{task_id}")
def delete_quadrant_task(runtime_id: str, task_id: int):
    """删除四象限任务
    
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.delete(agent_id=agent_id, task_id=task_id)


@router.post("/rt/{runtime_id}/quadrant-tasks/{task_id}/start")
def start_quadrant_task(runtime_id: str, task_id: int):
    """开始执行四象限任务
    
    将任务状态设为 in_progress 并返回任务详情。
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.start_task(agent_id=agent_id, task_id=task_id)


class TaskProgressRequest(BaseModel):
    note: str
    set_ongoing: bool = False


@router.post("/rt/{runtime_id}/quadrant-tasks/{task_id}/progress")
def add_task_progress(runtime_id: str, task_id: int, request: TaskProgressRequest):
    """记录任务进展
    
    用于持续性任务，记录阶段性进展。
    供 tools_server 调用的内部 API。
    """
    from gateway.db.repositories.task import TaskRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = TaskRepository(db)
    
    return repo.add_progress(
        agent_id=agent_id,
        task_id=task_id,
        note=request.note,
        set_ongoing=request.set_ongoing,
    )


@router.post("/rt/{runtime_id}/growth-logs")
def log_growth(runtime_id: str, request: GrowthLogRequest):
    """记录成长日志
    
    供 tools_server 调用的内部 API。
    存储到 agent_drive.growth_log JSON 字段（如果存在）或 notebook。
    """
    from gateway.db.repositories.notebook import NotebookRepository
    
    _, agent_id, _ = resolve_runtime_ids(runtime_id)
    
    db = get_db()
    repo = NotebookRepository(db)
    
    # 使用 notebook 存储成长日志
    return repo.write(
        agent_id=agent_id,
        entry_type="reflection",  # 成长日志作为反思类型
        title=f"Growth Log: {request.category}",
        content=request.content,
        source=f"runtime:{runtime_id}",
        related_topics=[request.category, "growth"],
        relevance_score=0.7,  # 成长日志有较高相关性
    )
