"""
Internal API module: task

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== TaskManager API (for Tools Server) ====================

@router.post("/tasks/spawn")
def task_spawn(data: Dict[str, Any]):
    """Spawn a new task.
    
    Used by Tools Server to create background tasks.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    result = task_manager.spawn(
        task_type=data.get("task_type", "tool"),
        config=data.get("config", {}),
        label=data.get("label"),
        timeout_seconds=data.get("timeout_seconds", 0),
        notify_on=data.get("notify_on"),
        parent_session_key=data.get("parent_session_key"),
        agent_id=data.get("agent_id"),
    )
    return result


@router.post("/tasks/create-completed")
def task_create_completed(data: Dict[str, Any]):
    """Create an immediately completed task for truncated output storage.
    
    Used by Tools Server for _auto_truncate_result.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    task_id = task_manager.create_completed(
        tool_name=data.get("tool_name", "unknown"),
        truncated_result=data.get("truncated_result", ""),
        full_output=data.get("full_output", ""),
        ttl_hours=data.get("ttl_hours", 24),
        agent_id=data.get("agent_id"),
    )
    return {"task_id": task_id}


@router.get("/tasks/{task_id}")
def task_get_status(
    task_id: str,
    include_outputs: bool = False,
    start_line: Optional[int] = None,
    end_line: Optional[int] = None,
    tail_lines: Optional[int] = None,
):
    """Get task status by ID.
    
    Used by Tools Server for task_query tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.get_status(
        task_id=task_id,
        include_outputs=include_outputs,
        start_line=start_line,
        end_line=end_line,
        tail_lines=tail_lines,
    )


@router.get("/tasks")
def task_list(
    status: Optional[str] = None,
    agent_id: Optional[str] = None,
):
    """List tasks.
    
    Used by Tools Server for task_list tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    status_filter = [status] if status else None
    return task_manager.get_status(
        task_id=None,
        status_filter=status_filter,
        agent_id=agent_id,
    )


@router.post("/tasks/{task_id}/cancel")
def task_cancel(task_id: str, reason: Optional[str] = None):
    """Cancel a task.
    
    Used by Tools Server for task_cancel tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.cancel(task_id, reason)


@router.get("/tasks/{task_id}/result")
def task_get_result(task_id: str, format: str = "summary"):
    """Get task result.
    
    Used by Tools Server for task_result tool.
    """
    from gateway.core.task_manager import get_task_manager
    
    task_manager = get_task_manager()
    if not task_manager:
        raise HTTPException(status_code=503, detail="TaskManager not available")
    
    return task_manager.get_result(task_id, format=format)
