"""
Internal API module: vm

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== SSH Key API (for Tools Server) ====================

@router.get("/vm/ssh/public-key")
def get_ssh_public_key():
    """Get default SSH public key.
    
    Used by Tools Server (qemudebug) to inject SSH key into VM.
    """
    from gateway.vm.ssh import get_ssh_key_manager
    
    manager = get_ssh_key_manager()
    public_key = manager.get_public_key()
    
    return {"public_key": public_key}


@router.get("/vm/ssh/private-key-path")
def get_ssh_private_key_path():
    """Get path to SSH private key file.
    
    Used by Tools Server (qemudebug) for SSH connections.
    Returns the path where Gateway has written the private key.
    """
    from gateway.vm.ssh import get_ssh_key_manager
    
    manager = get_ssh_key_manager()
    key_path = manager.get_private_key_path()
    
    return {"key_path": str(key_path)}



# ---------- VM Tools Discovery API ----------

@router.get("/runtimes/{runtime_id}/vm-tools")
def get_runtime_vm_tools(runtime_id: str):
    """
    获取 Runtime 的 VM 工具列表
    
    用于 Tools Server 发现 VM 工具（不通过 MCP）。
    如果 Runtime 关联的 Agent 有 VM 配置，返回 vmuse_adapter 定义的工具列表。
    
    Args:
        runtime_id: Runtime ID (rt-xxx)
    
    Returns:
        {
            "tools": [...],  # VM 工具列表（MCP 格式）
            "agent_id": "...",
            "vm_available": true/false
        }
    """
    from gateway.db.repositories import RuntimeRepository
    from gateway.clients.vmuse_adapter import get_vmuse_adapter
    from gateway.config.agents import get_agent_config_manager
    
    # 1. 检查 Runtime 是否存在
    db = get_db()
    runtime_repo = RuntimeRepository(db)
    runtime = runtime_repo.get_by_id(runtime_id)
    
    if not runtime:
        raise HTTPException(status_code=404, detail=f"Runtime not found: {runtime_id}")
    
    agent_id = runtime.agent_id
    if not agent_id:
        return {"tools": [], "vm_available": False}
    
    # 2. 获取 Agent 配置，检查是否有 VM
    config_mgr = get_agent_config_manager()
    try:
        agent = config_mgr.get_agent(agent_id)
    except Exception as e:
        # Agent 配置不存在
        return {"tools": [], "vm_available": False, "error": str(e)}
    
    # 3. 检查 VM 配置
    if not hasattr(agent, 'vm') or not agent.vm:
        return {"tools": [], "agent_id": agent_id, "vm_available": False}
    
    # 4. 使用 vmuse_adapter 获取工具列表
    try:
        adapter = get_vmuse_adapter()
        tools = adapter.list_tools_mcp_format()  # 使用新的 MCP 格式方法
        
        return {
            "tools": tools,
            "agent_id": agent_id,
            "vm_available": True
        }
    except Exception as e:
        return {
            "tools": [],
            "agent_id": agent_id,
            "vm_available": False,
            "error": f"Failed to get VM tools: {str(e)}"
        }
