"""
Internal API module: vm

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter

from .helpers import resolve_agent_id_from_subagent

router = APIRouter(tags=["internal"])

# ==================== SSH Key API (for Tools Server) ====================

@router.get("/vm/ssh/public-key")
def get_ssh_public_key():
    """Get default SSH public key.
    
    Used by Tools Server (qemudebug) to inject SSH key into VM.
    """
    from gateway.vm.ssh import get_ssh_key_manager
    
    manager = get_ssh_key_manager()
    public_key = manager.get_public_key()
    
    return {"public_key": public_key}


@router.get("/vm/ssh/private-key-path")
def get_ssh_private_key_path():
    """Get path to SSH private key file.
    
    Used by Tools Server (qemudebug) for SSH connections.
    Returns the path where Gateway has written the private key.
    """
    from gateway.vm.ssh import get_ssh_key_manager
    
    manager = get_ssh_key_manager()
    key_path = manager.get_private_key_path()
    
    return {"key_path": str(key_path)}



# ---------- VM Tools Discovery API ----------

@router.get("/subagents/{subagent_id}/vm-tools")
async def get_subagent_vm_tools(subagent_id: str):
    """
    获取 SubAgent 所属 Agent 的 VM 工具列表。

    Gateway business API: subagent_id-only input, no runtime lookup.
    """
    from gateway.config.agents import get_agent_config_manager
    from common.tools import VM_TOOLS

    agent_id = resolve_agent_id_from_subagent(subagent_id)

    if not agent_id:
        return {"tools": [], "vm_available": False}

    config_mgr = get_agent_config_manager()
    try:
        agent = config_mgr.get_agent(agent_id)
    except Exception as e:
        return {"tools": [], "vm_available": False, "error": str(e)}

    if not hasattr(agent, "vm") or not agent.vm:
        return {"tools": [], "agent_id": agent_id, "vm_available": False}

    try:
        tools = VM_TOOLS
        return {
            "tools": tools,
            "agent_id": agent_id,
            "vm_available": True,
        }
    except Exception as e:
        return {
            "tools": [],
            "agent_id": agent_id,
            "vm_available": False,
            "error": f"Failed to get VM tools: {str(e)}",
        }

