"""
Internal API module: web

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime
import json

from common.enums import RuntimeStatus, SubagentStatus
from common.config import ServiceConfig
from gateway.db.access import get_db
from .helpers import resolve_runtime_ids, get_runtime_context, _runtime_to_dict, _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Web API (for Tools Server local tools) ====================
# NOTE: Legacy Chat API (/chat/*) removed in v15.
# Use Runtime-First API: /rt/{runtime_id}/chat/* instead.

@router.post("/web/search")
def web_search(data: Dict[str, Any]):
    """Search the web using Brave Search API.
    
    Used by Tools Server for web_search tool.
    """
    import os

    BRAVE_API_KEY = os.environ.get("BRAVE_API_KEY", "")
    
    if not BRAVE_API_KEY:
        return {
            "error": "BRAVE_API_KEY not configured",
            "results": []
        }
    
    query = data.get("query", "")
    count = min(data.get("count", 10), 20)
    freshness = data.get("freshness")
    
    try:
        from common.http.clients import external_client
        with external_client(timeout=30.0) as client:
            params = {"q": query, "count": count}
            if freshness:
                params["freshness"] = freshness
            
            response = client.get(
                "https://api.search.brave.com/res/v1/web/search",
                params=params,
                headers={
                    "Accept": "application/json",
                    "X-Subscription-Token": BRAVE_API_KEY
                }
            )
            response.raise_for_status()
            api_data = response.json()
            
            results = []
            for item in api_data.get("web", {}).get("results", []):
                results.append({
                    "title": item.get("title", ""),
                    "url": item.get("url", ""),
                    "description": item.get("description", ""),
                    "age": item.get("age", "")
                })
            
            return {
                "results": results,
                "query": query,
                "total_count": api_data.get("web", {}).get("total", len(results))
            }
    except Exception as e:
        return {"error": str(e), "results": []}


@router.post("/web/fetch")
def web_fetch(data: Dict[str, Any]):
    """Fetch a web page and convert to markdown.
    
    Used by Tools Server for web_fetch tool.
    """
    import re

    url = data.get("url", "")
    extract_main_content = data.get("extract_main_content", True)
    max_length = data.get("max_length", 50000)
    
    try:
        from common.http.clients import external_client
        with external_client(
            timeout=30.0,
            follow_redirects=True,
            headers={
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
            }
        ) as client:
            response = client.get(url)
            response.raise_for_status()
            
            html_content = response.text
            title = ""
            content = ""
            
            if extract_main_content:
                try:
                    from readability import Document
                    doc = Document(html_content)
                    title = doc.title()
                    html_content = doc.summary()
                except Exception:
                    pass
            
            # Convert HTML to markdown
            try:
                import html2text
                h = html2text.HTML2Text()
                h.ignore_links = False
                h.ignore_images = False
                h.body_width = 0
                content = h.handle(html_content)
            except Exception:
                from bs4 import BeautifulSoup
                soup = BeautifulSoup(html_content, "html.parser")
                if not title:
                    title_tag = soup.find("title")
                    title = title_tag.get_text() if title_tag else ""
                content = soup.get_text(separator="\n", strip=True)
            
            if not title:
                from bs4 import BeautifulSoup
                soup = BeautifulSoup(response.text, "html.parser")
                title_tag = soup.find("title")
                title = title_tag.get_text() if title_tag else url
            
            content = re.sub(r'\n{3,}', '\n\n', content).strip()
            
            if len(content) > max_length:
                content = content[:max_length] + "\n\n... [Content truncated]"
            
            return {
                "url": url,
                "title": title,
                "content": content,
                "word_count": len(content.split()),
                "success": True
            }
    except Exception as e:
        return {"url": url, "error": str(e), "success": False}
