"""
Internal API module: agent

Auto-generated by split_internal_api.py
"""

from fastapi import APIRouter, HTTPException, Query, Request
from typing import Optional, List, Dict, Any, Tuple, TYPE_CHECKING
from datetime import datetime, timedelta
import json
import uuid
import logging

logger = logging.getLogger(__name__)

from common.enums import RuntimeStatus, SubagentStatus
from common.utils.time import utc_now
from business.device_client import (
    resolve_agent_runtime_context,
    get_available_tools_for_agent,
    proxy_qemu_request,
)

from .helpers import _subagent_to_dict

router = APIRouter(tags=["internal"])

# ==================== Agent Operations ====================

@router.get("/agents/setup-complete")
def get_setup_complete_agents():
    """Get all agents with setup complete."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    # Scoped globally (user_id="")
    agents = store.list("agents", "", filters={"setup_complete": 1})
    agent_ids = [agent["id"] for agent in agents]
    
    return {"agent_ids": agent_ids}


@router.post("/agents/{agent_id}/awake")
def set_agent_awake(agent_id: str):
    """Set agent state to awake."""
    from business.entity_store import get_entity_store
    from common.utils.time import utc_now_iso
    
    store = get_entity_store()
    now = utc_now_iso()
    store.upsert(
        "agent-state", "", agent_id,
        data={
            "state": "awake",
            "rest_reason": None,
            "wake_triggers": [],
            "rest_started_at": None,
            "last_active_at": now
        },
        params={"agent_id": agent_id}
    )
    
    return {"status": "ok"}


@router.post("/agents/{agent_id}/sleep")
def set_agent_sleep(agent_id: str, data: Dict[str, Any] = None):
    """Set agent state to sleep."""
    from business.entity_store import get_entity_store
    from common.utils.time import utc_now_iso
    
    store = get_entity_store()
    reason = (data or {}).get("reason", "Task completed")
    now = utc_now_iso()
    
    store.upsert(
        "agent-state", "", agent_id,
        data={
            "state": "sleep",
            "rest_reason": reason,
            "rest_started_at": now,
            "last_active_at": now
        },
        params={"agent_id": agent_id}
    )
    
    return {"status": "ok"}


@router.get("/agents/{agent_id}")
def get_agent_internal(agent_id: str):
    """Get agent information for internal use (tools server).
    
    Returns vm.ports and android for VM tools (screenshot, desktop)
    and mobile tools, using unified devices as the source of truth.
    """
    from business.entity_store import get_entity_store as _get_store

    store = _get_store()
    agent_row = store.get("agents", "", agent_id)
    if not agent_row:
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    agent_pk = agent_row.get("id") or agent_id
    agent_name = agent_row.get("name") or ""
    owner_user_id = agent_row.get("user_id") or ""

    bindings = store.list("agent-binding", "", params={"agent_id": agent_id}) or []
    if not bindings:
        single = store.get("agent-binding", "", agent_id)
        if single:
            bindings = [single]
    devices: List[Dict[str, Any]] = []
    seen_ids = set()
    for binding in bindings:
        did = binding.get("device_id")
        if not did or did in seen_ids:
            continue
        seen_ids.add(did)
        device_row = store.get("devices", owner_user_id, did) or store.get("devices", "", did)
        if device_row:
            devices.append(device_row)

    resolved = resolve_agent_runtime_context(agent_id)
    if resolved is not None:
        result = {
            "agent_id": agent_pk,
            "name": agent_name,
            "binding": resolved["binding"],
            "mounted_tools": resolved["mounted_tools"],
            "supported_tools": resolved["supported_tools"],
            "subject": resolved["subject"],
            "runtime_context": resolved["runtime_context"],
        }
        device = resolved["device"]
        if device.get("type") == "linux":
            result["vm"] = {
                "backend": device.get("backend"),
                "ports": device.get("ports", {}),
            }
        elif device.get("type") == "android":
            result["android"] = {
                "device_serial": device.get("device_serial", "") or "",
                "managed": device.get("managed", True),
                "avd_name": device.get("avd_name", "") or "",
            }
        return result

    linux_device = None
    android_device = None
    for device in devices:
        if not isinstance(device, dict):
            continue
        if device.get("type") == "linux" and linux_device is None:
            linux_device = device
        elif device.get("type") == "android" and android_device is None:
            android_device = device
        if linux_device and android_device:
            break

    vm_ports = {"ssh": None, "vmuse": None}
    vm_backend = None
    if linux_device:
        ports = linux_device.get("ports") or {}
        if isinstance(ports, str):
            try:
                ports = json.loads(ports)
            except (json.JSONDecodeError, TypeError):
                ports = {}
        vm_ports["ssh"] = ports.get("ssh")
        vm_ports["vmuse"] = ports.get("vmuse")
        vm_backend = linux_device.get("backend")

    result = {
        "agent_id": agent_pk,
        "name": agent_name,
        "vm": {
            "backend": vm_backend,
            "ports": vm_ports,
        } if linux_device else {}
    }

    if android_device:
        result["android"] = {
            "device_serial": android_device.get("device_serial", "") or "",
            "managed": android_device.get("managed", True),
            "avd_name": android_device.get("avd_name", ""),
        }
    
    return result


def _filter_builtin_tools_for_agent(agent_id: str) -> List[Dict[str, Any]]:
    """
    Filter BUILTIN_TOOLS for an agent based on disabled_tools, binding, and mounted_tools.
    
    vm/mobile 工具不在 BUILTIN_TOOLS 中，根据 device mount 动态添加：
    - Linux device: VM_TOOLS（需 mounted 的按 mounted_tools 过滤，其余有 binding 即可）
    - Android device: MOBILE_TOOLS（按 mounted_tools 过滤）
    """
    from common.tools import BUILTIN_TOOLS, VM_TOOLS, MOBILE_TOOLS, QEMU_TOOLS, HD_TOOLS

    # Flatten BUILTIN_TOOLS (不含 vm/mobile)
    all_tools: List[tuple] = []
    for category, tools_list in BUILTIN_TOOLS.items():
        for t in tools_list:
            all_tools.append((category, t))

    # Get disabled_tools from agent_drive via EntityStore
    from business.entity_store import get_entity_store
    store = get_entity_store()
    drive = store.get("agent-tools", "", agent_id, params={"agent_id": agent_id})
    disabled = set(drive.get("disabled_tools", [])) if drive else set()

    # Binding + mount maps from Device Service (HTTP)
    tools_payload = get_available_tools_for_agent(agent_id)
    device_type = tools_payload.get("device_type")
    if device_type is not None:
        device_type = str(device_type).lower()
        if "." in device_type:
            device_type = device_type.split(".")[-1]
    mounted: Dict[str, List[str]] = dict(tools_payload.get("mounted") or {})
    tool_name_to_mounted: Dict[str, Any] = tools_payload.get("tool_name_to_mounted") or {}

    result: List[Dict[str, Any]] = []

    # 1. Builtin 工具（memory, notebook, chat 等）
    for category, t in all_tools:
        name = t.get("name", "")
        if name in disabled:
            continue
        result.append(_tool_for_response(t))

    def _rule_matches(name: str) -> bool:
        rule = tool_name_to_mounted.get(name)
        if not rule or len(rule) < 3:
            return False
        _dev_type, cat, op = rule[0], rule[1], rule[2]
        return op in mounted.get(cat, [])

    # 2. QEMU 工具：仅当 device_type=linux 且 qemu 已 mount 时添加
    if device_type == "linux":
        for t in QEMU_TOOLS:
            name = t.get("name", "")
            if name in disabled:
                continue
            if _rule_matches(name):
                result.append(_tool_for_response(t))

    # 3. VM 工具：仅当 device_type=linux 时，根据 mounted_tools 添加
    if device_type == "linux":
        for t in VM_TOOLS:
            name = t.get("name", "")
            if name in disabled:
                continue
            if tool_name_to_mounted.get(name) is not None:
                if _rule_matches(name):
                    result.append(_tool_for_response(t))
            else:
                # VM 工具不在 TOOL_NAME_TO_MOUNTED 中（browser_*, list_windows 等）：有 binding 即可
                result.append(_tool_for_response(t))

    # 4. Mobile 工具：仅当 device_type=android 时，根据 mounted_tools 添加
    if device_type == "android":
        for t in MOBILE_TOOLS:
            name = t.get("name", "")
            if name in disabled:
                continue
            if _rule_matches(name):
                result.append(_tool_for_response(t))

    # 5. HD 工具：仅当 device_type=host_desktop 时，根据 mounted_tools 添加
    if device_type == "host_desktop":
        for t in HD_TOOLS:
            name = t.get("name", "")
            if name in disabled:
                continue
            if _rule_matches(name):
                result.append(_tool_for_response(t))

    return result


def _tool_for_response(t: Dict[str, Any]) -> Dict[str, Any]:
    """Extract name, description, inputSchema for API response."""
    return {
        "name": t.get("name", ""),
        "description": t.get("description", ""),
        "inputSchema": t.get("inputSchema", {}),
    }


@router.get("/agents/{agent_id}/builtin-tools")
def get_agent_builtin_tools(agent_id: str):
    """
    Get filtered builtin tools for an agent (internal API).
    
    Used by Tools Server to obtain tools already filtered by disabled_tools
    and mounted_tools (VM/mobile). Returns tools with name, description, inputSchema.
    """
    tools = _filter_builtin_tools_for_agent(agent_id)
    return {"tools": tools, "total": len(tools)}


@router.get("/agents/{agent_id}/tools-config")
def get_agent_tools_config_internal(agent_id: str):
    """
    Get agent's tools config (disabled_tools) for internal use.
    
    No user auth - used by Tools Server fallback when builtin-tools fails.
    """
    from business.entity_store import get_entity_store
    store = get_entity_store()
    drive = store.get("agent-tools", "", agent_id, params={"agent_id": agent_id})
    if not drive:
        return {"agent_id": agent_id, "disabled_tools": [], "custom_instructions": ""}
    return {
        "agent_id": agent_id,
        "disabled_tools": drive.get("disabled_tools", []),
        "custom_instructions": drive.get("custom_instructions", ""),
    }


@router.get("/agents/{agent_id}/memory/all")
def get_all_agent_memory(agent_id: str):
    """Get all memory data for an agent (all namespaces).
    
    Used by system_prompt builder to auto-load memory into system prompt.
    
    Returns:
        {
            "success": True,
            "namespaces": {
                "default": {"key1": "value1", ...},
                "preferences": {...},
                ...
            }
        }
    """
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    
    # 既然有 namespace, 先得把所有这个 agent 下的 key v拿出来
    all_memories = store.list("agent-memory", "", params={"agent_id": agent_id})
    result = {}
    for entry in all_memories:
        ns = entry.get("namespace", "default")
        if ns not in result:
            result[ns] = {}
        result[ns][entry.get("key")] = entry.get("value")
    
    return {
        "success": True,
        "namespaces": result
    }


# ==================== Memory CRUD (agent-scoped; migrated from /internal/rt/*) ====================

@router.post("/agents/{agent_id}/memory/save")
def memory_save(agent_id: str, data: Dict[str, Any]):
    """Save memory value. Replaces /internal/rt/{runtime_id}/memory/save."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    key = data.get("key", "")
    namespace = data.get("namespace", "default")
    value = data.get("value")
    
    # agent_memory has composite UNIQUE(agent_id, namespace, key).
    # store.upsert uses ON CONFLICT(id_field) which won't match the composite constraint.
    # Do manual get → update/create instead.
    params = {"agent_id": agent_id, "namespace": namespace}
    existing = store.get("agent-memory", "", str(key), params=params)
    if existing:
        # id_field for agent-memory is "key", so entity_id must be the key value
        store.update("agent-memory", "", str(key), {"value": value}, params=params)
    else:
        store.create("agent-memory", "", {
            "agent_id": agent_id,
            "namespace": namespace,
            "key": key,
            "value": value,
        }, params=params)
    
    return {
        "success": True,
        "key": key,
        "namespace": namespace
    }


@router.post("/agents/{agent_id}/memory/recall")
def memory_recall(agent_id: str, data: Dict[str, Any]):
    """Recall memory value. Replaces /internal/rt/{runtime_id}/memory/recall."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    key = data.get("key")
    namespace = data.get("namespace", "default")
    
    if key:
        entry = store.get("agent-memory", "", str(key), params={"agent_id": agent_id, "namespace": namespace})
        if entry:
            return {
                "success": True,
                "key": key,
                "value": entry.get("value"),
                "updated_at": entry.get("updated_at"),
                "found": True
            }
        else:
            return {
                "success": True,
                "key": key,
                "value": None,
                "found": False
            }
    else:
        entries = store.list("agent-memory", "", params={"agent_id": agent_id, "namespace": namespace})
        memories = {e.get("key"): e.get("value") for e in entries if isinstance(e, dict)}
        
        return {
            "success": True,
            "namespace": namespace,
            "memories": memories,
            "count": len(memories)
        }


@router.post("/agents/{agent_id}/memory/delete")
def memory_delete(agent_id: str, data: Dict[str, Any]):
    """Delete memory value. Replaces /internal/rt/{runtime_id}/memory/delete."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    key = data.get("key", "")
    namespace = data.get("namespace", "default")
    
    ok = store.delete("agent-memory", "", str(key), params={"agent_id": agent_id, "namespace": namespace})
    
    return {
        "success": True,
        "key": key,
        "deleted": ok
    }


@router.get("/agents/{agent_id}/memory/namespaces")
def memory_list_namespaces(agent_id: str):
    """List memory namespaces. Replaces /internal/rt/{runtime_id}/memory/namespaces."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    entries = store.list("agent-memory", "", params={"agent_id": agent_id})
    ns = list(set([e.get("namespace", "default") for e in entries]))
    
    return {"success": True, "namespaces": ns}


@router.post("/agents/{agent_id}/memory/task/log")
def memory_log_task(agent_id: str, data: Dict[str, Any]):
    """Log task action. Replaces /internal/rt/{runtime_id}/memory/task/log."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    action = data.get("action", "")
    details = data.get("details")
    status = data.get("status", "completed")
    
    entry = store.create(
        "agent-task-history", "",
        data={
            "action": action,
            "details": details,
            "status": status,
        },
        params={"agent_id": agent_id}
    )
    
    count = store.count("agent-task-history", "", params={"agent_id": agent_id})
    
    return {
        "success": True,
        "logged": {
            "action": action,
            "details": details,
            "status": status,
            "timestamp": entry.get("timestamp")
        },
        "history_count": count
    }


@router.post("/agents/{agent_id}/memory/task/history")
def memory_get_task_history(agent_id: str, data: Dict[str, Any]):
    """Get task history. Replaces /internal/rt/{runtime_id}/memory/task/history."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    limit = data.get("limit", 20)
    status_filter = data.get("status_filter")
    
    entries = store.list("agent-task-history", "", params={"agent_id": agent_id})
    total_count = len(entries)
    
    if status_filter:
        entries = [e for e in entries if e.get("status") == status_filter]
        
    filtered_count = len(entries)
    
    # Sort descending
    entries.sort(key=lambda x: str(x.get("timestamp") or ""), reverse=True)
    entries = entries[:limit]
    
    # Needs to return older first based on original implementation logic "history.reverse() # Oldest first"
    entries.reverse()
    
    return {
        "success": True,
        "history": entries,
        "total_count": total_count,
        "filtered_count": filtered_count
    }


# ==================== Notebook CRUD (agent-scoped; migrated from /internal/rt/*) ====================

@router.post("/agents/{agent_id}/notebook/write")
def notebook_write(agent_id: str, data: Dict[str, Any]):
    """Write notebook entry. Replaces /internal/rt/{runtime_id}/notebook/write."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    entry = store.create(
        "agent-notebook", "",
        data={
            "entry_type": data.get("entry_type", "memo"),
            "title": data.get("title", ""),
            "content": data.get("content", ""),
            "source": data.get("source"),
            "related_topics": data.get("related_topics", []),
            "relevance_score": max(0.0, min(1.0, data.get("relevance_score", 0.5))),
            "status": "draft",
            "expires_at": data.get("expires_at"),
        },
        params={"agent_id": agent_id}
    )
    
    return {
        "success": True,
        "id": entry.get("id"),
        "entry_type": entry.get("entry_type"),
        "title": entry.get("title"),
        "status": entry.get("status"),
    }


@router.post("/agents/{agent_id}/notebook/list")
def notebook_list(agent_id: str, data: Dict[str, Any]):
    """List notebook entries. Replaces /internal/rt/{runtime_id}/notebook/list."""
    from business.entity_store import get_entity_store
    from common.utils.time import utc_now_iso
    
    store = get_entity_store()
    
    # Pre-filter all since EntityStore list doesn't natively do advanced filtering yet
    entries = store.list("agent-notebook", "", params={"agent_id": agent_id})
    
    entry_type = data.get("entry_type")
    if entry_type:
        entries = [e for e in entries if e.get("entry_type") == entry_type]
        
    status = data.get("status")
    if status:
        entries = [e for e in entries if e.get("status") == status]
        
    include_expired = data.get("include_expired", False)
    if not include_expired:
        now = utc_now_iso()
        entries = [e for e in entries if not e.get("expires_at") or e.get("expires_at") > now]
        
    # Sort DESC by default
    entries = sorted(entries, key=lambda x: x.get("created_at", ""), reverse=True)
    limit = data.get("limit", 20)
    entries = entries[:limit]
    
    return {
        "success": True,
        "entries": entries,
        "count": len(entries),
    }


@router.post("/agents/{agent_id}/notebook/read")
def notebook_read(agent_id: str, data: Dict[str, Any]):
    """Read notebook entry. Replaces /internal/rt/{runtime_id}/notebook/read."""
    from business.entity_store import get_entity_store
    
    entry_id = data.get("entry_id")
    if entry_id is None:
        raise HTTPException(status_code=400, detail="entry_id is required")
        
    store = get_entity_store()
    entry = store.get("agent-notebook", "", str(entry_id), params={"agent_id": agent_id})
    
    if not entry:
        return {"success": True, "found": False, "entry": None}
        
    return {
        "success": True,
        "found": True,
        "entry": entry,
    }


@router.post("/agents/{agent_id}/notebook/update")
def notebook_update(agent_id: str, data: Dict[str, Any]):
    """Update notebook entry. Replaces /internal/rt/{runtime_id}/notebook/update."""
    from business.entity_store import get_entity_store
    
    entry_id = data.get("entry_id")
    if entry_id is None:
        raise HTTPException(status_code=400, detail="entry_id is required")
        
    updates = {}
    if "status" in data: updates["status"] = data["status"]
    if "content" in data: updates["content"] = data["content"]
    if "title" in data: updates["title"] = data["title"]
    if "relevance_score" in data: updates["relevance_score"] = data["relevance_score"]
    if "expires_at" in data: updates["expires_at"] = data["expires_at"]
    
    store = get_entity_store()
    if updates:
        store.update("agent-notebook", "", str(entry_id), updates, params={"agent_id": agent_id})
        
    return {"success": True, "id": entry_id}


# ==================== Drive (agent-scoped; migrated from /internal/rt/*) ====================

@router.post("/agents/{agent_id}/drive/update-profile")
def drive_update_profile(agent_id: str, data: Dict[str, Any]):
    """Update drive profile. Replaces /internal/rt/{runtime_id}/drive/update-profile."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    current = store.get("agent-tools", "", agent_id, params={"agent_id": agent_id})
    if not current:
        current = {"user_profile": {}}
    
    profile = current.get("user_profile", {})
    key = data.get("key", "")
    profile[key] = data.get("value")
    
    store.upsert(
        "agent-tools", "", agent_id,
        data={"user_profile": profile},
        params={"agent_id": agent_id}
    )
    
    return {
        "success": True,
        "key": key,
        "profile_keys": list(profile.keys()),
    }


@router.post("/agents/{agent_id}/drive/update")
def drive_update(agent_id: str, data: Dict[str, Any]):
    """Update drive relationship. Replaces /internal/rt/{runtime_id}/drive/update."""
    from business.entity_store import get_entity_store
    
    store = get_entity_store()
    current = store.get("agent-tools", "", agent_id, params={"agent_id": agent_id})
    if not current:
        current = {"relationship_level": 0, "proactiveness": 0.5}
        
    updates = {}
    rel_delta = data.get("relationship_delta")
    if rel_delta is not None:
        updates["relationship_level"] = max(0, min(100, current.get("relationship_level", 0) + rel_delta))
        
    proact_delta = data.get("proactiveness_delta")
    if proact_delta is not None:
        updates["proactiveness"] = max(0.0, min(1.0, current.get("proactiveness", 0.5) + proact_delta))
        
    if updates:
        store.upsert(
            "agent-tools", "", agent_id,
            data=updates,
            params={"agent_id": agent_id}
        )
        
    return {"success": True, "agent_id": agent_id}


# QEMU endpoints now served by Device Service

@router.get("/agents/{agent_id}/qemu/status")
async def qemu_status(agent_id: str):
    return await proxy_qemu_request("GET", f"/agents/{agent_id}/qemu/status")


@router.post("/agents/{agent_id}/qemu/ssh-exec")
async def qemu_ssh_exec(agent_id: str, data: Dict[str, Any]):
    return await proxy_qemu_request("POST", f"/agents/{agent_id}/qemu/ssh-exec", data)


@router.post("/agents/{agent_id}/qemu/start")
async def qemu_start(agent_id: str, data: Dict[str, Any]):
    return await proxy_qemu_request("POST", f"/agents/{agent_id}/qemu/start", data)


@router.post("/agents/{agent_id}/qemu/shutdown")
async def qemu_shutdown(agent_id: str, data: Dict[str, Any]):
    return await proxy_qemu_request("POST", f"/agents/{agent_id}/qemu/shutdown", data)


@router.post("/agents/{agent_id}/qemu/restart")
async def qemu_restart(agent_id: str, data: Dict[str, Any]):
    return await proxy_qemu_request("POST", f"/agents/{agent_id}/qemu/restart", data)


# ==================== SubAgent APIs (agent-scoped; replaces /internal/rt/*/subagent/*) ====================

@router.post("/agents/{agent_id}/subagent/spawn")
async def agent_subagent_spawn(agent_id: str, data: Dict[str, Any]):
    """Spawn a SubAgent. parent_subagent_id from body (caller's subagent_id)."""
    parent_subagent_id = data.get("parent_subagent_id")
    if not parent_subagent_id:
        raise HTTPException(status_code=400, detail="parent_subagent_id is required")

    from business.entity_store import get_entity_store
    from business.internal.subagent_utils import ensure_agent_stub
    from common.utils.time import utc_now_iso
    import json as _json

    store = get_entity_store()

    task_description = data.get("task", "")
    timeout_minutes = data.get("timeout_minutes", 30)

    now = utc_now()
    timeout_at = (now + timedelta(minutes=timeout_minutes)).isoformat()

    ensure_agent_stub(None, agent_id)
    sub_id = f"sub-{uuid.uuid4().hex[:12]}"
    store.create("subagents", "", {
        "subagent_id": sub_id,
        "agent_id": agent_id,
        "type": "sub",
        "parent_subagent_id": parent_subagent_id,
        "status": "sleeping",
        "task": task_description,
        "timeout_at": timeout_at,
    })

    initial_context = [{"role": "user", "content": f"[SubAgent Task]\n{task_description}"}]

    trigger_id = f"spawn-{sub_id}-{uuid.uuid4().hex[:8]}"
    msg_id = uuid.uuid4().hex[:12]
    msg = store.append("messages", "", {
        "id": msg_id,
        "agent_id": agent_id,
        "type": "SPAWN_SUBAGENT",
        "content": task_description,
        "read": 0,
        "status": "sent",
        "metadata": _json.dumps({
            "subagent_id": sub_id,
            "trigger_id": trigger_id,
            "initial_context": initial_context,
            "parent_subagent_id": parent_subagent_id,
        }),
        "timestamp": utc_now_iso(),
    }, params={"agent_id": agent_id}) or {"id": msg_id}

    return {
        "subagent_id": sub_id,
        "message_id": msg["id"],
    }


@router.get("/agents/{agent_id}/subagent/{target_subagent_id}/status")
async def agent_subagent_status(agent_id: str, target_subagent_id: str):
    """Query SubAgent status."""
    from business.entity_store import get_entity_store

    store = get_entity_store()

    subagent = store.get("subagents", "", target_subagent_id, params={"agent_id": agent_id})
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")

    if subagent["status"] == SubagentStatus.RUNNING.value and subagent.get("timeout_at"):
        try:
            timeout_at = datetime.fromisoformat(subagent["timeout_at"])
            if utc_now() > timeout_at:
                store.update("subagents", "", target_subagent_id,
                    {"status": SubagentStatus.FAILED.value, "error": "SubAgent timed out", "progress": None},
                    params={"agent_id": agent_id})
                subagent = store.get("subagents", "", target_subagent_id, params={"agent_id": agent_id})
        except (ValueError, TypeError) as e:
            logger.warning("[Agent] Invalid timeout_at format for subagent %s: %s", target_subagent_id, e)

    completed = subagent["status"] in (
        SubagentStatus.COMPLETED.value,
        SubagentStatus.FAILED.value,
        SubagentStatus.CANCELLED.value,
        SubagentStatus.SLEEPING.value,
    )

    return {
        "subagent_id": target_subagent_id,
        "status": subagent["status"],
        "completed": completed,
        "progress": subagent.get("progress"),
        "result": subagent.get("result"),
        "error": subagent.get("error"),
    }


@router.post("/agents/{agent_id}/subagent/{target_subagent_id}/cancel")
async def agent_subagent_cancel(agent_id: str, target_subagent_id: str):
    """Cancel a running SubAgent."""
    from business.entity_store import get_entity_store

    store = get_entity_store()
    subagent = store.get("subagents", "", target_subagent_id, params={"agent_id": agent_id})
    if not subagent:
        raise HTTPException(status_code=404, detail="SubAgent not found")

    if subagent["status"] != SubagentStatus.RUNNING.value:
        return {"success": False, "error": f"SubAgent is not running (status: {subagent['status']})"}

    store.update("subagents", "", target_subagent_id,
        {"status": SubagentStatus.CANCELLED.value, "progress": None},
        params={"agent_id": agent_id})

    return {"success": True}


@router.post("/agents/{agent_id}/subagent/report")
async def agent_subagent_report(agent_id: str, data: Dict[str, Any]):
    """Report result for Sub SubAgent. subagent_id from body. B2: Gateway handles locally."""
    from business.entity_store import get_entity_store

    subagent_id = data.get("subagent_id")
    if not subagent_id or not subagent_id.startswith("sub-"):
        return {
            "success": False,
            "error": "subagent_report is only available for Sub SubAgents (subagent_id must start with 'sub-')",
        }

    result = data.get("result")
    if not result:
        return {"success": False, "error": "result is required"}

    store = get_entity_store()
    subagent = store.get("subagents", "", subagent_id, params={"agent_id": agent_id})
    if not subagent:
        return {"success": False, "error": "SubAgent not found"}

    store.update("subagents", "", subagent_id, {"result": result}, params={"agent_id": agent_id})
    return {
        "success": True,
        "subagent_id": subagent_id,
        "message": "Result reported successfully. Parent agent can now query your findings.",
    }


# VM/Mobile/HD proxy routes now served by Device Service (:19993)
# See novaic-device/device/agent_vm_proxy.py
